package com.datatrees.rawdatacentral.domain.model;

import java.io.Serializable;
import java.util.Date;

public class AppCrawlerConfig implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_crawler_config
     * @mbg.generated
     */
    private static final long    serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_crawler_config.id
     * @mbg.generated
     */
    private              Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_crawler_config.website_type
     * @mbg.generated
     */
    private              Byte    websiteType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_crawler_config.app_id
     * @mbg.generated
     */
    private              String  appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_crawler_config.project
     * @mbg.generated
     */
    private              String  project;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_crawler_config.crawler_status
     * @mbg.generated
     */
    private              Boolean crawlerStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_crawler_config.created_at
     * @mbg.generated
     */
    private              Date    createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_crawler_config.updated_at
     * @mbg.generated
     */
    private              Date    updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_crawler_config.id
     * @return the value of app_crawler_config.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_crawler_config.id
     * @param id the value for app_crawler_config.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_crawler_config.website_type
     * @return the value of app_crawler_config.website_type
     * @mbg.generated
     */
    public Byte getWebsiteType() {
        return websiteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_crawler_config.website_type
     * @param websiteType the value for app_crawler_config.website_type
     * @mbg.generated
     */
    public void setWebsiteType(Byte websiteType) {
        this.websiteType = websiteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_crawler_config.app_id
     * @return the value of app_crawler_config.app_id
     * @mbg.generated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_crawler_config.app_id
     * @param appId the value for app_crawler_config.app_id
     * @mbg.generated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_crawler_config.project
     * @return the value of app_crawler_config.project
     * @mbg.generated
     */
    public String getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_crawler_config.project
     * @param project the value for app_crawler_config.project
     * @mbg.generated
     */
    public void setProject(String project) {
        this.project = project == null ? null : project.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_crawler_config.crawler_status
     * @return the value of app_crawler_config.crawler_status
     * @mbg.generated
     */
    public Boolean getCrawlerStatus() {
        return crawlerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_crawler_config.crawler_status
     * @param crawlerStatus the value for app_crawler_config.crawler_status
     * @mbg.generated
     */
    public void setCrawlerStatus(Boolean crawlerStatus) {
        this.crawlerStatus = crawlerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_crawler_config.created_at
     * @return the value of app_crawler_config.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_crawler_config.created_at
     * @param createdAt the value for app_crawler_config.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_crawler_config.updated_at
     * @return the value of app_crawler_config.updated_at
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_crawler_config.updated_at
     * @param updatedAt the value for app_crawler_config.updated_at
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_crawler_config
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", websiteType=").append(websiteType);
        sb.append(", appId=").append(appId);
        sb.append(", project=").append(project);
        sb.append(", crawlerStatus=").append(crawlerStatus);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append("]");
        return sb.toString();
    }
}