package com.datatrees.rawdatacentral.domain.model;

import java.io.Serializable;
import java.util.Date;

public class WebsiteInfo implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table website_info
     * @mbg.generated
     */
    private static final long    serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.search_config
     * @mbg.generated
     */
    private              String  searchConfig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.extractor_config
     * @mbg.generated
     */
    private              String  extractorConfig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.website_id
     * @mbg.generated
     */
    private              Integer websiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.env
     * @mbg.generated
     */
    private              String  env;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.website_type
     * @mbg.generated
     */
    private              Integer websiteType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.website_name
     * @mbg.generated
     */
    private              String  websiteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.website_title
     * @mbg.generated
     */
    private              String  websiteTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.enable
     * @mbg.generated
     */
    private              Boolean enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.proxy_enable
     * @mbg.generated
     */
    private              Boolean proxyEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.group_code
     * @mbg.generated
     */
    private              String  groupCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.updated_at
     * @mbg.generated
     */
    private              Date    updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.start_stage
     * @mbg.generated
     */
    private              String  startStage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.login_url
     * @mbg.generated
     */
    private              String  loginUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.plugin_class
     * @mbg.generated
     */
    private              String  pluginClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.login_config
     * @mbg.generated
     */
    private              String  loginConfig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.sms_interval
     * @mbg.generated
     */
    private              Integer smsInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.remark
     * @mbg.generated
     */
    private              String  remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.login_tip
     * @mbg.generated
     */
    private              String  loginTip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.verify_tip
     * @mbg.generated
     */
    private              String  verifyTip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.reset_type
     * @mbg.generated
     */
    private              String  resetType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.sms_template
     * @mbg.generated
     */
    private              String  smsTemplate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.sms_receiver
     * @mbg.generated
     */
    private              String  smsReceiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.reset_url
     * @mbg.generated
     */
    private              String  resetUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.reset_tip
     * @mbg.generated
     */
    private              String  resetTip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.created_at
     * @mbg.generated
     */
    private              Date    createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website_info.attribute
     * @mbg.generated
     */
    private              String  attribute;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.website_id
     * @return the value of website_info.website_id
     * @mbg.generated
     */
    public Integer getWebsiteId() {
        return websiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.website_id
     * @param websiteId the value for website_info.website_id
     * @mbg.generated
     */
    public void setWebsiteId(Integer websiteId) {
        this.websiteId = websiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.env
     * @return the value of website_info.env
     * @mbg.generated
     */
    public String getEnv() {
        return env;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.env
     * @param env the value for website_info.env
     * @mbg.generated
     */
    public void setEnv(String env) {
        this.env = env == null ? null : env.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.website_type
     * @return the value of website_info.website_type
     * @mbg.generated
     */
    public Integer getWebsiteType() {
        return websiteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.website_type
     * @param websiteType the value for website_info.website_type
     * @mbg.generated
     */
    public void setWebsiteType(Integer websiteType) {
        this.websiteType = websiteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.website_name
     * @return the value of website_info.website_name
     * @mbg.generated
     */
    public String getWebsiteName() {
        return websiteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.website_name
     * @param websiteName the value for website_info.website_name
     * @mbg.generated
     */
    public void setWebsiteName(String websiteName) {
        this.websiteName = websiteName == null ? null : websiteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.website_title
     * @return the value of website_info.website_title
     * @mbg.generated
     */
    public String getWebsiteTitle() {
        return websiteTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.website_title
     * @param websiteTitle the value for website_info.website_title
     * @mbg.generated
     */
    public void setWebsiteTitle(String websiteTitle) {
        this.websiteTitle = websiteTitle == null ? null : websiteTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.enable
     * @return the value of website_info.enable
     * @mbg.generated
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.enable
     * @param enable the value for website_info.enable
     * @mbg.generated
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.proxy_enable
     * @return the value of website_info.proxy_enable
     * @mbg.generated
     */
    public Boolean getProxyEnable() {
        return proxyEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.proxy_enable
     * @param proxyEnable the value for website_info.proxy_enable
     * @mbg.generated
     */
    public void setProxyEnable(Boolean proxyEnable) {
        this.proxyEnable = proxyEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.group_code
     * @return the value of website_info.group_code
     * @mbg.generated
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.group_code
     * @param groupCode the value for website_info.group_code
     * @mbg.generated
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode == null ? null : groupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.updated_at
     * @return the value of website_info.updated_at
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.updated_at
     * @param updatedAt the value for website_info.updated_at
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.start_stage
     * @return the value of website_info.start_stage
     * @mbg.generated
     */
    public String getStartStage() {
        return startStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.start_stage
     * @param startStage the value for website_info.start_stage
     * @mbg.generated
     */
    public void setStartStage(String startStage) {
        this.startStage = startStage == null ? null : startStage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.login_url
     * @return the value of website_info.login_url
     * @mbg.generated
     */
    public String getLoginUrl() {
        return loginUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.login_url
     * @param loginUrl the value for website_info.login_url
     * @mbg.generated
     */
    public void setLoginUrl(String loginUrl) {
        this.loginUrl = loginUrl == null ? null : loginUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.plugin_class
     * @return the value of website_info.plugin_class
     * @mbg.generated
     */
    public String getPluginClass() {
        return pluginClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.plugin_class
     * @param pluginClass the value for website_info.plugin_class
     * @mbg.generated
     */
    public void setPluginClass(String pluginClass) {
        this.pluginClass = pluginClass == null ? null : pluginClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.login_config
     * @return the value of website_info.login_config
     * @mbg.generated
     */
    public String getLoginConfig() {
        return loginConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.login_config
     * @param loginConfig the value for website_info.login_config
     * @mbg.generated
     */
    public void setLoginConfig(String loginConfig) {
        this.loginConfig = loginConfig == null ? null : loginConfig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.sms_interval
     * @return the value of website_info.sms_interval
     * @mbg.generated
     */
    public Integer getSmsInterval() {
        return smsInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.sms_interval
     * @param smsInterval the value for website_info.sms_interval
     * @mbg.generated
     */
    public void setSmsInterval(Integer smsInterval) {
        this.smsInterval = smsInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.remark
     * @return the value of website_info.remark
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.remark
     * @param remark the value for website_info.remark
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.login_tip
     * @return the value of website_info.login_tip
     * @mbg.generated
     */
    public String getLoginTip() {
        return loginTip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.login_tip
     * @param loginTip the value for website_info.login_tip
     * @mbg.generated
     */
    public void setLoginTip(String loginTip) {
        this.loginTip = loginTip == null ? null : loginTip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.verify_tip
     * @return the value of website_info.verify_tip
     * @mbg.generated
     */
    public String getVerifyTip() {
        return verifyTip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.verify_tip
     * @param verifyTip the value for website_info.verify_tip
     * @mbg.generated
     */
    public void setVerifyTip(String verifyTip) {
        this.verifyTip = verifyTip == null ? null : verifyTip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.reset_type
     * @return the value of website_info.reset_type
     * @mbg.generated
     */
    public String getResetType() {
        return resetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.reset_type
     * @param resetType the value for website_info.reset_type
     * @mbg.generated
     */
    public void setResetType(String resetType) {
        this.resetType = resetType == null ? null : resetType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.sms_template
     * @return the value of website_info.sms_template
     * @mbg.generated
     */
    public String getSmsTemplate() {
        return smsTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.sms_template
     * @param smsTemplate the value for website_info.sms_template
     * @mbg.generated
     */
    public void setSmsTemplate(String smsTemplate) {
        this.smsTemplate = smsTemplate == null ? null : smsTemplate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.sms_receiver
     * @return the value of website_info.sms_receiver
     * @mbg.generated
     */
    public String getSmsReceiver() {
        return smsReceiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.sms_receiver
     * @param smsReceiver the value for website_info.sms_receiver
     * @mbg.generated
     */
    public void setSmsReceiver(String smsReceiver) {
        this.smsReceiver = smsReceiver == null ? null : smsReceiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.reset_url
     * @return the value of website_info.reset_url
     * @mbg.generated
     */
    public String getResetUrl() {
        return resetUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.reset_url
     * @param resetUrl the value for website_info.reset_url
     * @mbg.generated
     */
    public void setResetUrl(String resetUrl) {
        this.resetUrl = resetUrl == null ? null : resetUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.reset_tip
     * @return the value of website_info.reset_tip
     * @mbg.generated
     */
    public String getResetTip() {
        return resetTip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.reset_tip
     * @param resetTip the value for website_info.reset_tip
     * @mbg.generated
     */
    public void setResetTip(String resetTip) {
        this.resetTip = resetTip == null ? null : resetTip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.created_at
     * @return the value of website_info.created_at
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.created_at
     * @param createdAt the value for website_info.created_at
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website_info.attribute
     * @return the value of website_info.attribute
     * @mbg.generated
     */
    public String getAttribute() {
        return attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website_info.attribute
     * @param attribute the value for website_info.attribute
     * @mbg.generated
     */
    public void setAttribute(String attribute) {
        this.attribute = attribute == null ? null : attribute.trim();
    }

    public String getSearchConfig() {
        return searchConfig;
    }

    public void setSearchConfig(String searchConfig) {
        this.searchConfig = searchConfig;
    }

    public String getExtractorConfig() {
        return extractorConfig;
    }

    public void setExtractorConfig(String extractorConfig) {
        this.extractorConfig = extractorConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table website_info
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", websiteId=").append(websiteId);
        sb.append(", env=").append(env);
        sb.append(", websiteType=").append(websiteType);
        sb.append(", websiteName=").append(websiteName);
        sb.append(", websiteTitle=").append(websiteTitle);
        sb.append(", enable=").append(enable);
        sb.append(", proxyEnable=").append(proxyEnable);
        sb.append(", groupCode=").append(groupCode);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", startStage=").append(startStage);
        sb.append(", loginUrl=").append(loginUrl);
        sb.append(", pluginClass=").append(pluginClass);
        sb.append(", loginConfig=").append(loginConfig);
        sb.append(", smsInterval=").append(smsInterval);
        sb.append(", remark=").append(remark);
        sb.append(", loginTip=").append(loginTip);
        sb.append(", verifyTip=").append(verifyTip);
        sb.append(", resetType=").append(resetType);
        sb.append(", smsTemplate=").append(smsTemplate);
        sb.append(", smsReceiver=").append(smsReceiver);
        sb.append(", resetUrl=").append(resetUrl);
        sb.append(", resetTip=").append(resetTip);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", attribute=").append(attribute);
        sb.append("]");
        return sb.toString();
    }
}