package com.datatrees.rawdatacentral.plugin.operator.hu_nan_10000_wap;

import javax.script.Invocable;
import java.util.List;
import java.util.Map;

import com.datatrees.crawler.core.util.xpath.XPathUtil;
import com.datatrees.rawdatacentral.common.http.TaskHttpClient;
import com.datatrees.rawdatacentral.common.utils.CheckUtils;
import com.datatrees.rawdatacentral.common.utils.ScriptEngineUtil;
import com.datatrees.rawdatacentral.common.utils.TemplateUtils;
import com.datatrees.rawdatacentral.domain.constant.FormType;
import com.datatrees.rawdatacentral.domain.enums.ErrorCode;
import com.datatrees.rawdatacentral.domain.enums.RequestType;
import com.datatrees.rawdatacentral.domain.operator.OperatorParam;
import com.datatrees.rawdatacentral.domain.result.HttpResult;
import com.datatrees.rawdatacentral.domain.vo.Response;
import com.datatrees.rawdatacentral.service.OperatorPluginService;
import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.lang3.StringUtils;
import org.joda.time.DateTime;
import org.joda.time.DurationFieldType;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Created by guimeichao on 17/9/25.
 */
public class HuNan10000ForWap implements OperatorPluginService {

    private static final Logger logger              = LoggerFactory.getLogger(HuNan10000ForWap.class);
    private static final String javaScript_mobile
                                                    = "ZnVuY3Rpb24gZW5jcnlwdFN0cihzKSB7DQoNCiAgICB2YXIga2V5U3RyID0gIkFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXowMTIzNDU2Nzg5Ky89IjsNCg0KICAgIHZhciBvdXRwdXQgPSAiIjsNCiAgICB2YXIgY2hyMSwgY2hyMiwgY2hyMyA9ICIiOw0KICAgIHZhciBlbmMxLCBlbmMyLCBlbmMzLCBlbmM0ID0gIiI7DQogICAgdmFyIGkgPSAwOw0KICAgIGRvIHsNCiAgICAgICAgY2hyMSA9IHMuY2hhckNvZGVBdChpKyspOw0KICAgICAgICBjaHIyID0gcy5jaGFyQ29kZUF0KGkrKyk7DQogICAgICAgIGNocjMgPSBzLmNoYXJDb2RlQXQoaSsrKTsNCiAgICAgICAgZW5jMSA9IGNocjEgPj4gMjsNCiAgICAgICAgZW5jMiA9ICgoY2hyMSAmIDMpIDw8IDQpIHwgKGNocjIgPj4gNCk7DQogICAgICAgIGVuYzMgPSAoKGNocjIgJiAxNSkgPDwgMikgfCAoY2hyMyA+PiA2KTsNCiAgICAgICAgZW5jNCA9IGNocjMgJiA2MzsNCiAgICAgICAgaWYgKGlzTmFOKGNocjIpKSB7DQogICAgICAgICAgICBlbmMzID0gZW5jNCA9IDY0Ow0KICAgICAgICB9IGVsc2UgaWYgKGlzTmFOKGNocjMpKSB7DQogICAgICAgICAgICBlbmM0ID0gNjQ7DQogICAgICAgIH0NCiAgICAgICAgb3V0cHV0ID0gb3V0cHV0ICsga2V5U3RyLmNoYXJBdChlbmMxKSArIGtleVN0ci5jaGFyQXQoZW5jMikNCiAgICAgICAgICAgICsga2V5U3RyLmNoYXJBdChlbmMzKSArIGtleVN0ci5jaGFyQXQoZW5jNCk7DQogICAgICAgIGNocjEgPSBjaHIyID0gY2hyMyA9ICIiOw0KICAgICAgICBlbmMxID0gZW5jMiA9IGVuYzMgPSBlbmM0ID0gIiI7DQogICAgfSB3aGlsZSAoaSA8IHMubGVuZ3RoKTsNCg0KICAgIHJldHVybiBvdXRwdXQ7DQp9Ow==";
    private static final String javaScript_password
                                                    = "ZnVuY3Rpb24gZW5jeXB0UHdkKHB3ZCl7DQogICAgdmFyIGtleSA7DQogICAgc2V0TWF4RGlnaXRzKDEzMCk7DQogICAga2V5ID0gbmV3IFJTQUtleVBhaXIoIjEwMDAxIiwiIiwiIik7DQogICAgcmV0dXJuIGVuY3J5cHRlZFN0cmluZyhrZXksIGVuY29kZVVSSUNvbXBvbmVudChwd2QpKTsNCn0NCi8vUlNBLCBhIHN1aXRlIG9mIHJvdXRpbmVzIGZvciBwZXJmb3JtaW5nIFJTQSBwdWJsaWMta2V5IGNvbXB1dGF0aW9ucyBpbg0KLy9KYXZhU2NyaXB0Lg0KLy8NCi8vUmVxdWlyZXMgQmlnSW50LmpzIGFuZCBCYXJyZXR0LmpzLg0KLy8NCi8vQ29weXJpZ2h0IDE5OTgtMjAwNSBEYXZpZCBTaGFwaXJvLg0KLy8NCi8vWW91IG1heSB1c2UsIHJlLXVzZSwgYWJ1c2UsIGNvcHksIGFuZCBtb2RpZnkgdGhpcyBjb2RlIHRvIHlvdXIgbGlraW5nLCBidXQNCi8vcGxlYXNlIGtlZXAgdGhpcyBoZWFkZXIuDQovLw0KLy9UaGFua3MhDQovLw0KLy9EYXZlIFNoYXBpcm8NCi8vZGF2ZUBvaGRhdmUuY29tDQoNCmZ1bmN0aW9uIFJTQUtleVBhaXIoZW5jcnlwdGlvbkV4cG9uZW50LCBkZWNyeXB0aW9uRXhwb25lbnQsIG1vZHVsdXMpDQp7DQogICAgdGhpcy5lID0gYmlGcm9tSGV4KGVuY3J5cHRpb25FeHBvbmVudCk7DQogICAgdGhpcy5kID0gYmlGcm9tSGV4KGRlY3J5cHRpb25FeHBvbmVudCk7DQogICAgdGhpcy5tID0gYmlGcm9tSGV4KCI5ZGIxM2IxNWZkNWJiMWU0MzM3Njc4YzZhZDFmZWIwNTM5MmNjYTkxZDEyZDJlZDk2YTNiOGViZTAyYWQzNTRiNzJkYmJmNThhZDU4ZTUyNDI4ZDYyZDllZGQ1ZDgyNGI1MDRmYTcwOTU1YjZlN2MyNjUwZWJlMDBjNmE4MWFkMzdiYTFmYmI5NWM3NTNiODQyOWQzMmQ3MzEyODU1ZDYxZmM4NzBkYzcyOWYzYmI5MTRhYjhlOTU4ZjQ4OGM1Zjk4ZDEwN2Y1ZjdkNWJmZWNhYjk5OWVkN2IxYjRiM2VjNjEwYTkzNDMwMDFkNWJhNmQ2MGRhM2RmZTM3NTIxYzVkIik7DQogICAgLy8gV2UgY2FuIGRvIHR3byBieXRlcyBwZXIgZGlnaXQsIHNvDQogICAgLy8gY2h1bmtTaXplID0gMiAqIChudW1iZXIgb2YgZGlnaXRzIGluIG1vZHVsdXMgLSAxKS4NCiAgICAvLyBTaW5jZSBiaUhpZ2hJbmRleCByZXR1cm5zIHRoZSBoaWdoIGluZGV4LCBub3QgdGhlIG51bWJlciBvZiBkaWdpdHMsIDEgaGFzDQogICAgLy8gYWxyZWFkeSBiZWVuIHN1YnRyYWN0ZWQuDQogICAgdGhpcy5jaHVua1NpemUgPSAyICogYmlIaWdoSW5kZXgodGhpcy5tKTsNCiAgICB0aGlzLnJhZGl4ID0gMTY7DQogICAgdGhpcy5iYXJyZXR0ID0gbmV3IEJhcnJldHRNdSh0aGlzLm0pOw0KfQ0KDQpmdW5jdGlvbiB0d29EaWdpdChuKQ0Kew0KICAgIHJldHVybiAobiA8IDEwID8gIjAiIDogIiIpICsgU3RyaW5nKG4pOw0KfQ0KDQpmdW5jdGlvbiBlbmNyeXB0ZWRTdHJpbmcoa2V5LCBzKQ0KLy8gQWx0ZXJlZCBieSBSb2IgU2F1bmRlcnMgKHJvYkByb2JzYXVuZGVycy5uZXQpLiBOZXcgcm91dGluZSBwYWRzIHRoZQ0KLy8gc3RyaW5nIGFmdGVyIGl0IGhhcyBiZWVuIGNvbnZlcnRlZCB0byBhbiBhcnJheS4gVGhpcyBmaXhlcyBhbg0KLy8gaW5jb21wYXRpYmlsaXR5IHdpdGggRmxhc2ggTVgncyBBY3Rpb25TY3JpcHQuDQp7DQogICAgdmFyIGEgPSBuZXcgQXJyYXkoKTsNCiAgICB2YXIgc2wgPSBzLmxlbmd0aDsNCiAgICB2YXIgaSA9IDA7DQogICAgd2hpbGUgKGkgPCBzbCkgew0KICAgICAgICBhW2ldID0gcy5jaGFyQ29kZUF0KGkpOw0KICAgICAgICBpKys7DQogICAgfQ0KDQogICAgd2hpbGUgKGEubGVuZ3RoICUga2V5LmNodW5rU2l6ZSAhPSAwKSB7DQogICAgICAgIGFbaSsrXSA9IDA7DQogICAgfQ0KDQogICAgdmFyIGFsID0gYS5sZW5ndGg7DQogICAgdmFyIHJlc3VsdCA9ICIiOw0KICAgIHZhciBqLCBrLCBibG9jazsNCiAgICBmb3IgKGkgPSAwOyBpIDwgYWw7IGkgKz0ga2V5LmNodW5rU2l6ZSkgew0KICAgICAgICBibG9jayA9IG5ldyBCaWdJbnQoKTsNCiAgICAgICAgaiA9IDA7DQogICAgICAgIGZvciAoayA9IGk7IGsgPCBpICsga2V5LmNodW5rU2l6ZTsgKytqKSB7DQogICAgICAgICAgICBibG9jay5kaWdpdHNbal0gPSBhW2srK107DQogICAgICAgICAgICBibG9jay5kaWdpdHNbal0gKz0gYVtrKytdIDw8IDg7DQogICAgICAgIH0NCiAgICAgICAgdmFyIGNyeXB0ID0ga2V5LmJhcnJldHQucG93TW9kKGJsb2NrLCBrZXkuZSk7DQogICAgICAgIHZhciB0ZXh0ID0ga2V5LnJhZGl4ID09IDE2ID8gYmlUb0hleChjcnlwdCkgOiBiaVRvU3RyaW5nKGNyeXB0LCBrZXkucmFkaXgpOw0KICAgICAgICByZXN1bHQgKz0gdGV4dCArICIgIjsNCiAgICB9DQogICAgcmV0dXJuIHJlc3VsdC5zdWJzdHJpbmcoMCwgcmVzdWx0Lmxlbmd0aCAtIDEpOyAvLyBSZW1vdmUgbGFzdCBzcGFjZS4NCn0NCg0KZnVuY3Rpb24gZGVjcnlwdGVkU3RyaW5nKGtleSwgcykNCnsNCiAgICB2YXIgYmxvY2tzID0gcy5zcGxpdCgiICIpOw0KICAgIHZhciByZXN1bHQgPSAiIjsNCiAgICB2YXIgaSwgaiwgYmxvY2s7DQogICAgZm9yIChpID0gMDsgaSA8IGJsb2Nrcy5sZW5ndGg7ICsraSkgew0KICAgICAgICB2YXIgYmk7DQogICAgICAgIGlmIChrZXkucmFkaXggPT0gMTYpIHsNCiAgICAgICAgICAgIGJpID0gYmlGcm9tSGV4KGJsb2Nrc1tpXSk7DQogICAgICAgIH0NCiAgICAgICAgZWxzZSB7DQogICAgICAgICAgICBiaSA9IGJpRnJvbVN0cmluZyhibG9ja3NbaV0sIGtleS5yYWRpeCk7DQogICAgICAgIH0NCiAgICAgICAgYmxvY2sgPSBrZXkuYmFycmV0dC5wb3dNb2QoYmksIGtleS5kKTsNCiAgICAgICAgZm9yIChqID0gMDsgaiA8PSBiaUhpZ2hJbmRleChibG9jayk7ICsraikgew0KICAgICAgICAgICAgcmVzdWx0ICs9IFN0cmluZy5mcm9tQ2hhckNvZGUoYmxvY2suZGlnaXRzW2pdICYgMjU1LA0KICAgICAgICAgICAgICAgIGJsb2NrLmRpZ2l0c1tqXSA+PiA4KTsNCiAgICAgICAgfQ0KICAgIH0NCiAgICAvLyBSZW1vdmUgdHJhaWxpbmcgbnVsbCwgaWYgYW55Lg0KICAgIGlmIChyZXN1bHQuY2hhckNvZGVBdChyZXN1bHQubGVuZ3RoIC0gMSkgPT0gMCkgew0KICAgICAgICByZXN1bHQgPSByZXN1bHQuc3Vic3RyaW5nKDAsIHJlc3VsdC5sZW5ndGggLSAxKTsNCiAgICB9DQogICAgcmV0dXJuIHJlc3VsdDsNCn0NCg0KLy9CaWdJbnQsIGEgc3VpdGUgb2Ygcm91dGluZXMgZm9yIHBlcmZvcm1pbmcgbXVsdGlwbGUtcHJlY2lzaW9uIGFyaXRobWV0aWMgaW4NCi8vSmF2YVNjcmlwdC4NCi8vDQovL0NvcHlyaWdodCAxOTk4LTIwMDUgRGF2aWQgU2hhcGlyby4NCi8vDQovL1lvdSBtYXkgdXNlLCByZS11c2UsIGFidXNlLA0KLy9jb3B5LCBhbmQgbW9kaWZ5IHRoaXMgY29kZSB0byB5b3VyIGxpa2luZywgYnV0IHBsZWFzZSBrZWVwIHRoaXMgaGVhZGVyLg0KLy9UaGFua3MhDQovLw0KLy9EYXZlIFNoYXBpcm8NCi8vZGF2ZUBvaGRhdmUuY29tDQoNCi8vSU1QT1JUQU5UIFRISU5HOiBCZSBzdXJlIHRvIHNldCBtYXhEaWdpdHMgYWNjb3JkaW5nIHRvIHlvdXIgcHJlY2lzaW9uDQovL25lZWRzLiBVc2UgdGhlIHNldE1heERpZ2l0cygpIGZ1bmN0aW9uIHRvIGRvIHRoaXMuIFNlZSBjb21tZW50cyBiZWxvdy4NCi8vDQovL1R3ZWFrZWQgYnkgSWFuIEJ1bm5pbmcNCi8vQWx0ZXJhdGlvbnM6DQovL0ZpeCBidWcgaW4gZnVuY3Rpb24gYmlGcm9tSGV4KHMpIHRvIGFsbG93DQovL3BhcnNpbmcgb2Ygc3RyaW5ncyBvZiBsZW5ndGggIT0gMCAobW9kIDQpDQoNCi8vQ2hhbmdlcyBtYWRlIGJ5IERhdmUgU2hhcGlybyBhcyBvZiAxMi8zMC8yMDA0Og0KLy8NCi8vVGhlIEJpZ0ludCgpIGNvbnN0cnVjdG9yIGRvZXNuJ3QgdGFrZSBhIHN0cmluZyBhbnltb3JlLiBJZiB5b3Ugd2FudCB0bw0KLy9jcmVhdGUgYSBCaWdJbnQgZnJvbSBhIHN0cmluZywgdXNlIGJpRnJvbURlY2ltYWwoKSBmb3IgYmFzZS0xMA0KLy9yZXByZXNlbnRhdGlvbnMsIGJpRnJvbUhleCgpIGZvciBiYXNlLTE2IHJlcHJlc2VudGF0aW9ucywgb3INCi8vYmlGcm9tU3RyaW5nKCkgZm9yIGJhc2UtMi10by0zNiByZXByZXNlbnRhdGlvbnMuDQovLw0KLy9iaUZyb21BcnJheSgpIGhhcyBiZWVuIHJlbW92ZWQuIFVzZSBiaUNvcHkoKSBpbnN0ZWFkLCBwYXNzaW5nIGEgQmlnSW50DQovL2luc3RlYWQgb2YgYW4gYXJyYXkuDQovLw0KLy9UaGUgQmlnSW50KCkgY29uc3RydWN0b3Igbm93IG9ubHkgY29uc3RydWN0cyBhIHplcm9lZC1vdXQgYXJyYXkuDQovL0FsdGVybmF0aXZlbHksIGlmIHlvdSBwYXNzIDx0cnVlPiwgaXQgd29uJ3QgY29uc3RydWN0IGFueSBhcnJheS4gU2VlIHRoZQ0KLy9iaUNvcHkoKSBtZXRob2QgZm9yIGFuIGV4YW1wbGUgb2YgdGhpcy4NCi8vDQovL0JlIHN1cmUgdG8gc2V0IG1heERpZ2l0cyBkZXBlbmRpbmcgb24geW91ciBwcmVjaXNpb24gbmVlZHMuIFRoZSBkZWZhdWx0DQovL3plcm9lZC1vdXQgYXJyYXkgWkVST19BUlJBWSBpcyBjb25zdHJ1Y3RlZCBpbnNpZGUgdGhlIHNldE1heERpZ2l0cygpDQovL2Z1bmN0aW9uLiBTbyB1c2UgdGhpcyBmdW5jdGlvbiB0byBzZXQgdGhlIHZhcmlhYmxlLiBET04nVCBKVVNUIFNFVCBUSEUNCi8vVkFMVUUuIFVTRSBUSEUgRlVOQ1RJT04uDQovLw0KLy9aRVJPX0FSUkFZIGV4aXN0cyB0byBob3BlZnVsbHkgc3BlZWQgdXAgY29uc3RydWN0aW9uIG9mIEJpZ0ludHMoKS4gQnkNCi8vcHJlY2FsY3VsYXRpbmcgdGhlIHplcm8gYXJyYXksIHdlIGNhbiBqdXN0IHVzZSBzbGljZSgwKSB0byBtYWtlIGNvcGllcyBvZg0KLy9pdC4gUHJlc3VtYWJseSB0aGlzIGNhbGxzIGZhc3RlciBuYXRpdmUgY29kZSwgYXMgb3Bwb3NlZCB0byBzZXR0aW5nIHRoZQ0KLy9lbGVtZW50cyBvbmUgYXQgYSB0aW1lLiBJIGhhdmUgbm90IGRvbmUgYW55IHRpbWluZyB0ZXN0cyB0byB2ZXJpZnkgdGhpcw0KLy9jbGFpbS4NCg0KLy9NYXggbnVtYmVyID0gMTBeMTYgLSAyID0gOTk5OTk5OTk5OTk5OTk5ODsNCi8vICAgICAgICAgICAgMl41MyAgICAgPSA5MDA3MTk5MjU0NzQwOTkyOw0KDQp2YXIgYmlSYWRpeEJhc2UgPSAyOw0KdmFyIGJpUmFkaXhCaXRzID0gMTY7DQp2YXIgYml0c1BlckRpZ2l0ID0gYmlSYWRpeEJpdHM7DQp2YXIgYmlSYWRpeCA9IDEgPDwgMTY7IC8vID0gMl4xNiA9IDY1NTM2DQp2YXIgYmlIYWxmUmFkaXggPSBiaVJhZGl4ID4+PiAxOw0KdmFyIGJpUmFkaXhTcXVhcmVkID0gYmlSYWRpeCAqIGJpUmFkaXg7DQp2YXIgbWF4RGlnaXRWYWwgPSBiaVJhZGl4IC0gMTsNCnZhciBtYXhJbnRlZ2VyID0gOTk5OTk5OTk5OTk5OTk5ODsNCg0KLy9tYXhEaWdpdHM6DQovL0NoYW5nZSB0aGlzIHRvIGFjY29tbW9kYXRlIHlvdXIgbGFyZ2VzdCBudW1iZXIgc2l6ZS4gVXNlIHNldE1heERpZ2l0cygpDQovL3RvIGNoYW5nZSBpdCENCi8vDQovL0luIGdlbmVyYWwsIGlmIHlvdSdyZSB3b3JraW5nIHdpdGggbnVtYmVycyBvZiBzaXplIE4gYml0cywgeW91J2xsIG5lZWQgMipODQovL2JpdHMgb2Ygc3RvcmFnZS4gRWFjaCBkaWdpdCBob2xkcyAxNiBiaXRzLiBTbywgYSAxMDI0LWJpdCBrZXkgd2lsbCBuZWVkDQovLw0KLy8xMDI0ICogMiAvIDE2ID0gMTI4IGRpZ2l0cyBvZiBzdG9yYWdlLg0KLy8NCg0KdmFyIG1heERpZ2l0czsNCnZhciBaRVJPX0FSUkFZOw0KdmFyIGJpZ1plcm8sIGJpZ09uZTsNCg0KZnVuY3Rpb24gc2V0TWF4RGlnaXRzKHZhbHVlKQ0Kew0KICAgIG1heERpZ2l0cyA9IHZhbHVlOw0KICAgIFpFUk9fQVJSQVkgPSBuZXcgQXJyYXkobWF4RGlnaXRzKTsNCiAgICBmb3IgKHZhciBpemEgPSAwOyBpemEgPCBaRVJPX0FSUkFZLmxlbmd0aDsgaXphKyspIFpFUk9fQVJSQVlbaXphXSA9IDA7DQogICAgYmlnWmVybyA9IG5ldyBCaWdJbnQoKTsNCiAgICBiaWdPbmUgPSBuZXcgQmlnSW50KCk7DQogICAgYmlnT25lLmRpZ2l0c1swXSA9IDE7DQp9DQoNCnNldE1heERpZ2l0cygyMCk7DQoNCi8vVGhlIG1heGltdW0gbnVtYmVyIG9mIGRpZ2l0cyBpbiBiYXNlIDEwIHlvdSBjYW4gY29udmVydCB0byBhbg0KLy9pbnRlZ2VyIHdpdGhvdXQgSmF2YVNjcmlwdCB0aHJvd2luZyB1cCBvbiB5b3UuDQp2YXIgZHBsMTAgPSAxNTsNCi8vbHIxMCA9IDEwIF4gZHBsMTANCnZhciBscjEwID0gYmlGcm9tTnVtYmVyKDEwMDAwMDAwMDAwMDAwMDApOw0KDQpmdW5jdGlvbiBCaWdJbnQoZmxhZykNCnsNCiAgICBpZiAodHlwZW9mIGZsYWcgPT0gImJvb2xlYW4iICYmIGZsYWcgPT0gdHJ1ZSkgew0KICAgICAgICB0aGlzLmRpZ2l0cyA9IG51bGw7DQogICAgfQ0KICAgIGVsc2Ugew0KICAgICAgICB0aGlzLmRpZ2l0cyA9IFpFUk9fQVJSQVkuc2xpY2UoMCk7DQogICAgfQ0KICAgIHRoaXMuaXNOZWcgPSBmYWxzZTsNCn0NCg0KZnVuY3Rpb24gYmlGcm9tRGVjaW1hbChzKQ0Kew0KICAgIHZhciBpc05lZyA9IHMuY2hhckF0KDApID09ICctJzsNCiAgICB2YXIgaSA9IGlzTmVnID8gMSA6IDA7DQogICAgdmFyIHJlc3VsdDsNCiAgICAvLyBTa2lwIGxlYWRpbmcgemVyb3MuDQogICAgd2hpbGUgKGkgPCBzLmxlbmd0aCAmJiBzLmNoYXJBdChpKSA9PSAnMCcpICsraTsNCiAgICBpZiAoaSA9PSBzLmxlbmd0aCkgew0KICAgICAgICByZXN1bHQgPSBuZXcgQmlnSW50KCk7DQogICAgfQ0KICAgIGVsc2Ugew0KICAgICAgICB2YXIgZGlnaXRDb3VudCA9IHMubGVuZ3RoIC0gaTsNCiAgICAgICAgdmFyIGZnbCA9IGRpZ2l0Q291bnQgJSBkcGwxMDsNCiAgICAgICAgaWYgKGZnbCA9PSAwKSBmZ2wgPSBkcGwxMDsNCiAgICAgICAgcmVzdWx0ID0gYmlGcm9tTnVtYmVyKE51bWJlcihzLnN1YnN0cihpLCBmZ2wpKSk7DQogICAgICAgIGkgKz0gZmdsOw0KICAgICAgICB3aGlsZSAoaSA8IHMubGVuZ3RoKSB7DQogICAgICAgICAgICByZXN1bHQgPSBiaUFkZChiaU11bHRpcGx5KHJlc3VsdCwgbHIxMCksDQogICAgICAgICAgICAgICAgYmlGcm9tTnVtYmVyKE51bWJlcihzLnN1YnN0cihpLCBkcGwxMCkpKSk7DQogICAgICAgICAgICBpICs9IGRwbDEwOw0KICAgICAgICB9DQogICAgICAgIHJlc3VsdC5pc05lZyA9IGlzTmVnOw0KICAgIH0NCiAgICByZXR1cm4gcmVzdWx0Ow0KfQ0KDQpmdW5jdGlvbiBiaUNvcHkoYmkpDQp7DQogICAgdmFyIHJlc3VsdCA9IG5ldyBCaWdJbnQodHJ1ZSk7DQogICAgcmVzdWx0LmRpZ2l0cyA9IGJpLmRpZ2l0cy5zbGljZSgwKTsNCiAgICByZXN1bHQuaXNOZWcgPSBiaS5pc05lZzsNCiAgICByZXR1cm4gcmVzdWx0Ow0KfQ0KDQpmdW5jdGlvbiBiaUZyb21OdW1iZXIoaSkNCnsNCiAgICB2YXIgcmVzdWx0ID0gbmV3IEJpZ0ludCgpOw0KICAgIHJlc3VsdC5pc05lZyA9IGkgPCAwOw0KICAgIGkgPSBNYXRoLmFicyhpKTsNCiAgICB2YXIgaiA9IDA7DQogICAgd2hpbGUgKGkgPiAwKSB7DQogICAgICAgIHJlc3VsdC5kaWdpdHNbaisrXSA9IGkgJiBtYXhEaWdpdFZhbDsNCiAgICAgICAgaSA9IE1hdGguZmxvb3IoaSAvIGJpUmFkaXgpOw0KICAgIH0NCiAgICByZXR1cm4gcmVzdWx0Ow0KfQ0KDQpmdW5jdGlvbiByZXZlcnNlU3RyKHMpDQp7DQogICAgdmFyIHJlc3VsdCA9ICIiOw0KICAgIGZvciAodmFyIGkgPSBzLmxlbmd0aCAtIDE7IGkgPiAtMTsgLS1pKSB7DQogICAgICAgIHJlc3VsdCArPSBzLmNoYXJBdChpKTsNCiAgICB9DQogICAgcmV0dXJuIHJlc3VsdDsNCn0NCg0KdmFyIGhleGF0cmlnZXNpbWFsVG9DaGFyID0gbmV3IEFycmF5KA0KICAgICcwJywgJzEnLCAnMicsICczJywgJzQnLCAnNScsICc2JywgJzcnLCAnOCcsICc5JywNCiAgICAnYScsICdiJywgJ2MnLCAnZCcsICdlJywgJ2YnLCAnZycsICdoJywgJ2knLCAnaicsDQogICAgJ2snLCAnbCcsICdtJywgJ24nLCAnbycsICdwJywgJ3EnLCAncicsICdzJywgJ3QnLA0KICAgICd1JywgJ3YnLCAndycsICd4JywgJ3knLCAneicNCik7DQoNCmZ1bmN0aW9uIGJpVG9TdHJpbmcoeCwgcmFkaXgpDQovLyAyIDw9IHJhZGl4IDw9IDM2DQp7DQogICAgdmFyIGIgPSBuZXcgQmlnSW50KCk7DQogICAgYi5kaWdpdHNbMF0gPSByYWRpeDsNCiAgICB2YXIgcXIgPSBiaURpdmlkZU1vZHVsbyh4LCBiKTsNCiAgICB2YXIgcmVzdWx0ID0gaGV4YXRyaWdlc2ltYWxUb0NoYXJbcXJbMV0uZGlnaXRzWzBdXTsNCiAgICB3aGlsZSAoYmlDb21wYXJlKHFyWzBdLCBiaWdaZXJvKSA9PSAxKSB7DQogICAgICAgIHFyID0gYmlEaXZpZGVNb2R1bG8ocXJbMF0sIGIpOw0KICAgICAgICBkaWdpdCA9IHFyWzFdLmRpZ2l0c1swXTsNCiAgICAgICAgcmVzdWx0ICs9IGhleGF0cmlnZXNpbWFsVG9DaGFyW3FyWzFdLmRpZ2l0c1swXV07DQogICAgfQ0KICAgIHJldHVybiAoeC5pc05lZyA/ICItIiA6ICIiKSArIHJldmVyc2VTdHIocmVzdWx0KTsNCn0NCg0KZnVuY3Rpb24gYmlUb0RlY2ltYWwoeCkNCnsNCiAgICB2YXIgYiA9IG5ldyBCaWdJbnQoKTsNCiAgICBiLmRpZ2l0c1swXSA9IDEwOw0KICAgIHZhciBxciA9IGJpRGl2aWRlTW9kdWxvKHgsIGIpOw0KICAgIHZhciByZXN1bHQgPSBTdHJpbmcocXJbMV0uZGlnaXRzWzBdKTsNCiAgICB3aGlsZSAoYmlDb21wYXJlKHFyWzBdLCBiaWdaZXJvKSA9PSAxKSB7DQogICAgICAgIHFyID0gYmlEaXZpZGVNb2R1bG8ocXJbMF0sIGIpOw0KICAgICAgICByZXN1bHQgKz0gU3RyaW5nKHFyWzFdLmRpZ2l0c1swXSk7DQogICAgfQ0KICAgIHJldHVybiAoeC5pc05lZyA/ICItIiA6ICIiKSArIHJldmVyc2VTdHIocmVzdWx0KTsNCn0NCg0KdmFyIGhleFRvQ2hhciA9IG5ldyBBcnJheSgnMCcsICcxJywgJzInLCAnMycsICc0JywgJzUnLCAnNicsICc3JywgJzgnLCAnOScsDQogICAgJ2EnLCAnYicsICdjJywgJ2QnLCAnZScsICdmJyk7DQoNCmZ1bmN0aW9uIGRpZ2l0VG9IZXgobikNCnsNCiAgICB2YXIgbWFzayA9IDB4ZjsNCiAgICB2YXIgcmVzdWx0ID0gIiI7DQogICAgZm9yIChpID0gMDsgaSA8IDQ7ICsraSkgew0KICAgICAgICByZXN1bHQgKz0gaGV4VG9DaGFyW24gJiBtYXNrXTsNCiAgICAgICAgbiA+Pj49IDQ7DQogICAgfQ0KICAgIHJldHVybiByZXZlcnNlU3RyKHJlc3VsdCk7DQp9DQoNCmZ1bmN0aW9uIGJpVG9IZXgoeCkNCnsNCiAgICB2YXIgcmVzdWx0ID0gIiI7DQogICAgdmFyIG4gPSBiaUhpZ2hJbmRleCh4KTsNCiAgICBmb3IgKHZhciBpID0gYmlIaWdoSW5kZXgoeCk7IGkgPiAtMTsgLS1pKSB7DQogICAgICAgIHJlc3VsdCArPSBkaWdpdFRvSGV4KHguZGlnaXRzW2ldKTsNCiAgICB9DQogICAgcmV0dXJuIHJlc3VsdDsNCn0NCg0KZnVuY3Rpb24gY2hhclRvSGV4KGMpDQp7DQogICAgdmFyIFpFUk8gPSA0ODsNCiAgICB2YXIgTklORSA9IFpFUk8gKyA5Ow0KICAgIHZhciBsaXR0bGVBID0gOTc7DQogICAgdmFyIGxpdHRsZVogPSBsaXR0bGVBICsgMjU7DQogICAgdmFyIGJpZ0EgPSA2NTsNCiAgICB2YXIgYmlnWiA9IDY1ICsgMjU7DQogICAgdmFyIHJlc3VsdDsNCg0KICAgIGlmIChjID49IFpFUk8gJiYgYyA8PSBOSU5FKSB7DQogICAgICAgIHJlc3VsdCA9IGMgLSBaRVJPOw0KICAgIH0gZWxzZSBpZiAoYyA+PSBiaWdBICYmIGMgPD0gYmlnWikgew0KICAgICAgICByZXN1bHQgPSAxMCArIGMgLSBiaWdBOw0KICAgIH0gZWxzZSBpZiAoYyA+PSBsaXR0bGVBICYmIGMgPD0gbGl0dGxlWikgew0KICAgICAgICByZXN1bHQgPSAxMCArIGMgLSBsaXR0bGVBOw0KICAgIH0gZWxzZSB7DQogICAgICAgIHJlc3VsdCA9IDA7DQogICAgfQ0KICAgIHJldHVybiByZXN1bHQ7DQp9DQoNCmZ1bmN0aW9uIGhleFRvRGlnaXQocykNCnsNCiAgICB2YXIgcmVzdWx0ID0gMDsNCiAgICB2YXIgc2wgPSBNYXRoLm1pbihzLmxlbmd0aCwgNCk7DQogICAgZm9yICh2YXIgaSA9IDA7IGkgPCBzbDsgKytpKSB7DQogICAgICAgIHJlc3VsdCA8PD0gNDsNCiAgICAgICAgcmVzdWx0IHw9IGNoYXJUb0hleChzLmNoYXJDb2RlQXQoaSkpDQogICAgfQ0KICAgIHJldHVybiByZXN1bHQ7DQp9DQoNCmZ1bmN0aW9uIGJpRnJvbUhleChzKQ0Kew0KICAgIHZhciByZXN1bHQgPSBuZXcgQmlnSW50KCk7DQogICAgdmFyIHNsID0gcy5sZW5ndGg7DQogICAgZm9yICh2YXIgaSA9IHNsLCBqID0gMDsgaSA+IDA7IGkgLT0gNCwgKytqKSB7DQogICAgICAgIHJlc3VsdC5kaWdpdHNbal0gPSBoZXhUb0RpZ2l0KHMuc3Vic3RyKE1hdGgubWF4KGkgLSA0LCAwKSwgTWF0aC5taW4oaSwgNCkpKTsNCiAgICB9DQogICAgcmV0dXJuIHJlc3VsdDsNCn0NCg0KZnVuY3Rpb24gYmlGcm9tU3RyaW5nKHMsIHJhZGl4KQ0Kew0KICAgIHZhciBpc05lZyA9IHMuY2hhckF0KDApID09ICctJzsNCiAgICB2YXIgaXN0b3AgPSBpc05lZyA/IDEgOiAwOw0KICAgIHZhciByZXN1bHQgPSBuZXcgQmlnSW50KCk7DQogICAgdmFyIHBsYWNlID0gbmV3IEJpZ0ludCgpOw0KICAgIHBsYWNlLmRpZ2l0c1swXSA9IDE7IC8vIHJhZGl4XjANCiAgICBmb3IgKHZhciBpID0gcy5sZW5ndGggLSAxOyBpID49IGlzdG9wOyBpLS0pIHsNCiAgICAgICAgdmFyIGMgPSBzLmNoYXJDb2RlQXQoaSk7DQogICAgICAgIHZhciBkaWdpdCA9IGNoYXJUb0hleChjKTsNCiAgICAgICAgdmFyIGJpRGlnaXQgPSBiaU11bHRpcGx5RGlnaXQocGxhY2UsIGRpZ2l0KTsNCiAgICAgICAgcmVzdWx0ID0gYmlBZGQocmVzdWx0LCBiaURpZ2l0KTsNCiAgICAgICAgcGxhY2UgPSBiaU11bHRpcGx5RGlnaXQocGxhY2UsIHJhZGl4KTsNCiAgICB9DQogICAgcmVzdWx0LmlzTmVnID0gaXNOZWc7DQogICAgcmV0dXJuIHJlc3VsdDsNCn0NCg0KZnVuY3Rpb24gYmlEdW1wKGIpDQp7DQogICAgcmV0dXJuIChiLmlzTmVnID8gIi0iIDogIiIpICsgYi5kaWdpdHMuam9pbigiICIpOw0KfQ0KDQpmdW5jdGlvbiBiaUFkZCh4LCB5KQ0Kew0KICAgIHZhciByZXN1bHQ7DQoNCiAgICBpZiAoeC5pc05lZyAhPSB5LmlzTmVnKSB7DQogICAgICAgIHkuaXNOZWcgPSAheS5pc05lZzsNCiAgICAgICAgcmVzdWx0ID0gYmlTdWJ0cmFjdCh4LCB5KTsNCiAgICAgICAgeS5pc05lZyA9ICF5LmlzTmVnOw0KICAgIH0NCiAgICBlbHNlIHsNCiAgICAgICAgcmVzdWx0ID0gbmV3IEJpZ0ludCgpOw0KICAgICAgICB2YXIgYyA9IDA7DQogICAgICAgIHZhciBuOw0KICAgICAgICBmb3IgKHZhciBpID0gMDsgaSA8IHguZGlnaXRzLmxlbmd0aDsgKytpKSB7DQogICAgICAgICAgICBuID0geC5kaWdpdHNbaV0gKyB5LmRpZ2l0c1tpXSArIGM7DQogICAgICAgICAgICByZXN1bHQuZGlnaXRzW2ldID0gbiAlIGJpUmFkaXg7DQogICAgICAgICAgICBjID0gTnVtYmVyKG4gPj0gYmlSYWRpeCk7DQogICAgICAgIH0NCiAgICAgICAgcmVzdWx0LmlzTmVnID0geC5pc05lZzsNCiAgICB9DQogICAgcmV0dXJuIHJlc3VsdDsNCn0NCg0KZnVuY3Rpb24gYmlTdWJ0cmFjdCh4LCB5KQ0Kew0KICAgIHZhciByZXN1bHQ7DQogICAgaWYgKHguaXNOZWcgIT0geS5pc05lZykgew0KICAgICAgICB5LmlzTmVnID0gIXkuaXNOZWc7DQogICAgICAgIHJlc3VsdCA9IGJpQWRkKHgsIHkpOw0KICAgICAgICB5LmlzTmVnID0gIXkuaXNOZWc7DQogICAgfSBlbHNlIHsNCiAgICAgICAgcmVzdWx0ID0gbmV3IEJpZ0ludCgpOw0KICAgICAgICB2YXIgbiwgYzsNCiAgICAgICAgYyA9IDA7DQogICAgICAgIGZvciAodmFyIGkgPSAwOyBpIDwgeC5kaWdpdHMubGVuZ3RoOyArK2kpIHsNCiAgICAgICAgICAgIG4gPSB4LmRpZ2l0c1tpXSAtIHkuZGlnaXRzW2ldICsgYzsNCiAgICAgICAgICAgIHJlc3VsdC5kaWdpdHNbaV0gPSBuICUgYmlSYWRpeDsNCiAgICAgICAgICAgIC8vIFN0dXBpZCBub24tY29uZm9ybWluZyBtb2R1bHVzIG9wZXJhdGlvbi4NCiAgICAgICAgICAgIGlmIChyZXN1bHQuZGlnaXRzW2ldIDwgMCkgcmVzdWx0LmRpZ2l0c1tpXSArPSBiaVJhZGl4Ow0KICAgICAgICAgICAgYyA9IDAgLSBOdW1iZXIobiA8IDApOw0KICAgICAgICB9DQogICAgICAgIC8vIEZpeCB1cCB0aGUgbmVnYXRpdmUgc2lnbiwgaWYgYW55Lg0KICAgICAgICBpZiAoYyA9PSAtMSkgew0KICAgICAgICAgICAgYyA9IDA7DQogICAgICAgICAgICBmb3IgKHZhciBpID0gMDsgaSA8IHguZGlnaXRzLmxlbmd0aDsgKytpKSB7DQogICAgICAgICAgICAgICAgbiA9IDAgLSByZXN1bHQuZGlnaXRzW2ldICsgYzsNCiAgICAgICAgICAgICAgICByZXN1bHQuZGlnaXRzW2ldID0gbiAlIGJpUmFkaXg7DQogICAgICAgICAgICAgICAgLy8gU3R1cGlkIG5vbi1jb25mb3JtaW5nIG1vZHVsdXMgb3BlcmF0aW9uLg0KICAgICAgICAgICAgICAgIGlmIChyZXN1bHQuZGlnaXRzW2ldIDwgMCkgcmVzdWx0LmRpZ2l0c1tpXSArPSBiaVJhZGl4Ow0KICAgICAgICAgICAgICAgIGMgPSAwIC0gTnVtYmVyKG4gPCAwKTsNCiAgICAgICAgICAgIH0NCiAgICAgICAgICAgIC8vIFJlc3VsdCBpcyBvcHBvc2l0ZSBzaWduIG9mIGFyZ3VtZW50cy4NCiAgICAgICAgICAgIHJlc3VsdC5pc05lZyA9ICF4LmlzTmVnOw0KICAgICAgICB9IGVsc2Ugew0KICAgICAgICAgICAgLy8gUmVzdWx0IGlzIHNhbWUgc2lnbi4NCiAgICAgICAgICAgIHJlc3VsdC5pc05lZyA9IHguaXNOZWc7DQogICAgICAgIH0NCiAgICB9DQogICAgcmV0dXJuIHJlc3VsdDsNCn0NCg0KDQpmdW5jdGlvbiBiaUhpZ2hJbmRleCh4KQ0Kew0KICAgIHZhciByZXN1bHQgPSB4LmRpZ2l0cy5sZW5ndGggLSAxOw0KICAgIHdoaWxlIChyZXN1bHQgPiAwICYmIHguZGlnaXRzW3Jlc3VsdF0gPT0gMCkgLS1yZXN1bHQ7DQogICAgcmV0dXJuIHJlc3VsdDsNCn0NCg0KZnVuY3Rpb24gYmlOdW1CaXRzKHgpDQp7DQogICAgdmFyIG4gPSBiaUhpZ2hJbmRleCh4KTsNCiAgICB2YXIgZCA9IHguZGlnaXRzW25dOw0KICAgIHZhciBtID0gKG4gKyAxKSAqIGJpdHNQZXJEaWdpdDsNCiAgICB2YXIgcmVzdWx0Ow0KICAgIGZvciAocmVzdWx0ID0gbTsgcmVzdWx0ID4gbSAtIGJpdHNQZXJEaWdpdDsgLS1yZXN1bHQpIHsNCiAgICAgICAgaWYgKChkICYgMHg4MDAwKSAhPSAwKSBicmVhazsNCiAgICAgICAgZCA8PD0gMTsNCiAgICB9DQogICAgcmV0dXJuIHJlc3VsdDsNCn0NCg0KZnVuY3Rpb24gYmlNdWx0aXBseSh4LCB5KQ0Kew0KICAgIHZhciByZXN1bHQgPSBuZXcgQmlnSW50KCk7DQogICAgdmFyIGM7DQogICAgdmFyIG4gPSBiaUhpZ2hJbmRleCh4KTsNCiAgICB2YXIgdCA9IGJpSGlnaEluZGV4KHkpOw0KICAgIHZhciB1LCB1diwgazsNCg0KICAgIGZvciAodmFyIGkgPSAwOyBpIDw9IHQ7ICsraSkgew0KICAgICAgICBjID0gMDsNCiAgICAgICAgayA9IGk7DQogICAgICAgIGZvciAoaiA9IDA7IGogPD0gbjsgKytqLCArK2spIHsNCiAgICAgICAgICAgIHV2ID0gcmVzdWx0LmRpZ2l0c1trXSArIHguZGlnaXRzW2pdICogeS5kaWdpdHNbaV0gKyBjOw0KICAgICAgICAgICAgcmVzdWx0LmRpZ2l0c1trXSA9IHV2ICYgbWF4RGlnaXRWYWw7DQogICAgICAgICAgICBjID0gdXYgPj4+IGJpUmFkaXhCaXRzOw0KICAgICAgICAgICAgLy9jID0gTWF0aC5mbG9vcih1diAvIGJpUmFkaXgpOw0KICAgICAgICB9DQogICAgICAgIHJlc3VsdC5kaWdpdHNbaSArIG4gKyAxXSA9IGM7DQogICAgfQ0KICAgIC8vIFNvbWVvbmUgZ2l2ZSBtZSBhIGxvZ2ljYWwgeG9yLCBwbGVhc2UuDQogICAgcmVzdWx0LmlzTmVnID0geC5pc05lZyAhPSB5LmlzTmVnOw0KICAgIHJldHVybiByZXN1bHQ7DQp9DQoNCmZ1bmN0aW9uIGJpTXVsdGlwbHlEaWdpdCh4LCB5KQ0Kew0KICAgIHZhciBuLCBjLCB1djsNCg0KICAgIHJlc3VsdCA9IG5ldyBCaWdJbnQoKTsNCiAgICBuID0gYmlIaWdoSW5kZXgoeCk7DQogICAgYyA9IDA7DQogICAgZm9yICh2YXIgaiA9IDA7IGogPD0gbjsgKytqKSB7DQogICAgICAgIHV2ID0gcmVzdWx0LmRpZ2l0c1tqXSArIHguZGlnaXRzW2pdICogeSArIGM7DQogICAgICAgIHJlc3VsdC5kaWdpdHNbal0gPSB1diAmIG1heERpZ2l0VmFsOw0KICAgICAgICBjID0gdXYgPj4+IGJpUmFkaXhCaXRzOw0KICAgICAgICAvL2MgPSBNYXRoLmZsb29yKHV2IC8gYmlSYWRpeCk7DQogICAgfQ0KICAgIHJlc3VsdC5kaWdpdHNbMSArIG5dID0gYzsNCiAgICByZXR1cm4gcmVzdWx0Ow0KfQ0KDQpmdW5jdGlvbiBhcnJheUNvcHkoc3JjLCBzcmNTdGFydCwgZGVzdCwgZGVzdFN0YXJ0LCBuKQ0Kew0KICAgIHZhciBtID0gTWF0aC5taW4oc3JjU3RhcnQgKyBuLCBzcmMubGVuZ3RoKTsNCiAgICBmb3IgKHZhciBpID0gc3JjU3RhcnQsIGogPSBkZXN0U3RhcnQ7IGkgPCBtOyArK2ksICsraikgew0KICAgICAgICBkZXN0W2pdID0gc3JjW2ldOw0KICAgIH0NCn0NCg0KdmFyIGhpZ2hCaXRNYXNrcyA9IG5ldyBBcnJheSgweDAwMDAsIDB4ODAwMCwgMHhDMDAwLCAweEUwMDAsIDB4RjAwMCwgMHhGODAwLA0KICAgIDB4RkMwMCwgMHhGRTAwLCAweEZGMDAsIDB4RkY4MCwgMHhGRkMwLCAweEZGRTAsDQogICAgMHhGRkYwLCAweEZGRjgsIDB4RkZGQywgMHhGRkZFLCAweEZGRkYpOw0KDQpmdW5jdGlvbiBiaVNoaWZ0TGVmdCh4LCBuKQ0Kew0KICAgIHZhciBkaWdpdENvdW50ID0gTWF0aC5mbG9vcihuIC8gYml0c1BlckRpZ2l0KTsNCiAgICB2YXIgcmVzdWx0ID0gbmV3IEJpZ0ludCgpOw0KICAgIGFycmF5Q29weSh4LmRpZ2l0cywgMCwgcmVzdWx0LmRpZ2l0cywgZGlnaXRDb3VudCwNCiAgICAgICAgcmVzdWx0LmRpZ2l0cy5sZW5ndGggLSBkaWdpdENvdW50KTsNCiAgICB2YXIgYml0cyA9IG4gJSBiaXRzUGVyRGlnaXQ7DQogICAgdmFyIHJpZ2h0Qml0cyA9IGJpdHNQZXJEaWdpdCAtIGJpdHM7DQogICAgZm9yICh2YXIgaSA9IHJlc3VsdC5kaWdpdHMubGVuZ3RoIC0gMSwgaTEgPSBpIC0gMTsgaSA+IDA7IC0taSwgLS1pMSkgew0KICAgICAgICByZXN1bHQuZGlnaXRzW2ldID0gKChyZXN1bHQuZGlnaXRzW2ldIDw8IGJpdHMpICYgbWF4RGlnaXRWYWwpIHwNCiAgICAgICAgICAgICgocmVzdWx0LmRpZ2l0c1tpMV0gJiBoaWdoQml0TWFza3NbYml0c10pID4+Pg0KICAgICAgICAgICAgKHJpZ2h0Qml0cykpOw0KICAgIH0NCiAgICByZXN1bHQuZGlnaXRzWzBdID0gKChyZXN1bHQuZGlnaXRzW2ldIDw8IGJpdHMpICYgbWF4RGlnaXRWYWwpOw0KICAgIHJlc3VsdC5pc05lZyA9IHguaXNOZWc7DQogICAgcmV0dXJuIHJlc3VsdDsNCn0NCg0KdmFyIGxvd0JpdE1hc2tzID0gbmV3IEFycmF5KDB4MDAwMCwgMHgwMDAxLCAweDAwMDMsIDB4MDAwNywgMHgwMDBGLCAweDAwMUYsDQogICAgMHgwMDNGLCAweDAwN0YsIDB4MDBGRiwgMHgwMUZGLCAweDAzRkYsIDB4MDdGRiwNCiAgICAweDBGRkYsIDB4MUZGRiwgMHgzRkZGLCAweDdGRkYsIDB4RkZGRik7DQoNCmZ1bmN0aW9uIGJpU2hpZnRSaWdodCh4LCBuKQ0Kew0KICAgIHZhciBkaWdpdENvdW50ID0gTWF0aC5mbG9vcihuIC8gYml0c1BlckRpZ2l0KTsNCiAgICB2YXIgcmVzdWx0ID0gbmV3IEJpZ0ludCgpOw0KICAgIGFycmF5Q29weSh4LmRpZ2l0cywgZGlnaXRDb3VudCwgcmVzdWx0LmRpZ2l0cywgMCwNCiAgICAgICAgeC5kaWdpdHMubGVuZ3RoIC0gZGlnaXRDb3VudCk7DQogICAgdmFyIGJpdHMgPSBuICUgYml0c1BlckRpZ2l0Ow0KICAgIHZhciBsZWZ0Qml0cyA9IGJpdHNQZXJEaWdpdCAtIGJpdHM7DQogICAgZm9yICh2YXIgaSA9IDAsIGkxID0gaSArIDE7IGkgPCByZXN1bHQuZGlnaXRzLmxlbmd0aCAtIDE7ICsraSwgKytpMSkgew0KICAgICAgICByZXN1bHQuZGlnaXRzW2ldID0gKHJlc3VsdC5kaWdpdHNbaV0gPj4+IGJpdHMpIHwNCiAgICAgICAgICAgICgocmVzdWx0LmRpZ2l0c1tpMV0gJiBsb3dCaXRNYXNrc1tiaXRzXSkgPDwgbGVmdEJpdHMpOw0KICAgIH0NCiAgICByZXN1bHQuZGlnaXRzW3Jlc3VsdC5kaWdpdHMubGVuZ3RoIC0gMV0gPj4+PSBiaXRzOw0KICAgIHJlc3VsdC5pc05lZyA9IHguaXNOZWc7DQogICAgcmV0dXJuIHJlc3VsdDsNCn0NCg0KZnVuY3Rpb24gYmlNdWx0aXBseUJ5UmFkaXhQb3dlcih4LCBuKQ0Kew0KICAgIHZhciByZXN1bHQgPSBuZXcgQmlnSW50KCk7DQogICAgYXJyYXlDb3B5KHguZGlnaXRzLCAwLCByZXN1bHQuZGlnaXRzLCBuLCByZXN1bHQuZGlnaXRzLmxlbmd0aCAtIG4pOw0KICAgIHJldHVybiByZXN1bHQ7DQp9DQoNCmZ1bmN0aW9uIGJpRGl2aWRlQnlSYWRpeFBvd2VyKHgsIG4pDQp7DQogICAgdmFyIHJlc3VsdCA9IG5ldyBCaWdJbnQoKTsNCiAgICBhcnJheUNvcHkoeC5kaWdpdHMsIG4sIHJlc3VsdC5kaWdpdHMsIDAsIHJlc3VsdC5kaWdpdHMubGVuZ3RoIC0gbik7DQogICAgcmV0dXJuIHJlc3VsdDsNCn0NCg0KZnVuY3Rpb24gYmlNb2R1bG9CeVJhZGl4UG93ZXIoeCwgbikNCnsNCiAgICB2YXIgcmVzdWx0ID0gbmV3IEJpZ0ludCgpOw0KICAgIGFycmF5Q29weSh4LmRpZ2l0cywgMCwgcmVzdWx0LmRpZ2l0cywgMCwgbik7DQogICAgcmV0dXJuIHJlc3VsdDsNCn0NCg0KZnVuY3Rpb24gYmlDb21wYXJlKHgsIHkpDQp7DQogICAgaWYgKHguaXNOZWcgIT0geS5pc05lZykgew0KICAgICAgICByZXR1cm4gMSAtIDIgKiBOdW1iZXIoeC5pc05lZyk7DQogICAgfQ0KICAgIGZvciAodmFyIGkgPSB4LmRpZ2l0cy5sZW5ndGggLSAxOyBpID49IDA7IC0taSkgew0KICAgICAgICBpZiAoeC5kaWdpdHNbaV0gIT0geS5kaWdpdHNbaV0pIHsNCiAgICAgICAgICAgIGlmICh4LmlzTmVnKSB7DQogICAgICAgICAgICAgICAgcmV0dXJuIDEgLSAyICogTnVtYmVyKHguZGlnaXRzW2ldID4geS5kaWdpdHNbaV0pOw0KICAgICAgICAgICAgfSBlbHNlIHsNCiAgICAgICAgICAgICAgICByZXR1cm4gMSAtIDIgKiBOdW1iZXIoeC5kaWdpdHNbaV0gPCB5LmRpZ2l0c1tpXSk7DQogICAgICAgICAgICB9DQogICAgICAgIH0NCiAgICB9DQogICAgcmV0dXJuIDA7DQp9DQoNCmZ1bmN0aW9uIGJpRGl2aWRlTW9kdWxvKHgsIHkpDQp7DQogICAgdmFyIG5iID0gYmlOdW1CaXRzKHgpOw0KICAgIHZhciB0YiA9IGJpTnVtQml0cyh5KTsNCiAgICB2YXIgb3JpZ1lJc05lZyA9IHkuaXNOZWc7DQogICAgdmFyIHEsIHI7DQogICAgaWYgKG5iIDwgdGIpIHsNCiAgICAgICAgLy8gfHh8IDwgfHl8DQogICAgICAgIGlmICh4LmlzTmVnKSB7DQogICAgICAgICAgICBxID0gYmlDb3B5KGJpZ09uZSk7DQogICAgICAgICAgICBxLmlzTmVnID0gIXkuaXNOZWc7DQogICAgICAgICAgICB4LmlzTmVnID0gZmFsc2U7DQogICAgICAgICAgICB5LmlzTmVnID0gZmFsc2U7DQogICAgICAgICAgICByID0gYmlTdWJ0cmFjdCh5LCB4KTsNCiAgICAgICAgICAgIC8vIFJlc3RvcmUgc2lnbnMsICdjYXVzZSB0aGV5J3JlIHJlZmVyZW5jZXMuDQogICAgICAgICAgICB4LmlzTmVnID0gdHJ1ZTsNCiAgICAgICAgICAgIHkuaXNOZWcgPSBvcmlnWUlzTmVnOw0KICAgICAgICB9IGVsc2Ugew0KICAgICAgICAgICAgcSA9IG5ldyBCaWdJbnQoKTsNCiAgICAgICAgICAgIHIgPSBiaUNvcHkoeCk7DQogICAgICAgIH0NCiAgICAgICAgcmV0dXJuIG5ldyBBcnJheShxLCByKTsNCiAgICB9DQoNCiAgICBxID0gbmV3IEJpZ0ludCgpOw0KICAgIHIgPSB4Ow0KDQogICAgLy8gTm9ybWFsaXplIFkuDQogICAgdmFyIHQgPSBNYXRoLmNlaWwodGIgLyBiaXRzUGVyRGlnaXQpIC0gMTsNCiAgICB2YXIgbGFtYmRhID0gMDsNCiAgICB3aGlsZSAoeS5kaWdpdHNbdF0gPCBiaUhhbGZSYWRpeCkgew0KICAgICAgICB5ID0gYmlTaGlmdExlZnQoeSwgMSk7DQogICAgICAgICsrbGFtYmRhOw0KICAgICAgICArK3RiOw0KICAgICAgICB0ID0gTWF0aC5jZWlsKHRiIC8gYml0c1BlckRpZ2l0KSAtIDE7DQogICAgfQ0KICAgIC8vIFNoaWZ0IHIgb3ZlciB0byBrZWVwIHRoZSBxdW90aWVudCBjb25zdGFudC4gV2UnbGwgc2hpZnQgdGhlDQogICAgLy8gcmVtYWluZGVyIGJhY2sgYXQgdGhlIGVuZC4NCiAgICByID0gYmlTaGlmdExlZnQociwgbGFtYmRhKTsNCiAgICBuYiArPSBsYW1iZGE7IC8vIFVwZGF0ZSB0aGUgYml0IGNvdW50IGZvciB4Lg0KICAgIHZhciBuID0gTWF0aC5jZWlsKG5iIC8gYml0c1BlckRpZ2l0KSAtIDE7DQoNCiAgICB2YXIgYiA9IGJpTXVsdGlwbHlCeVJhZGl4UG93ZXIoeSwgbiAtIHQpOw0KICAgIHdoaWxlIChiaUNvbXBhcmUociwgYikgIT0gLTEpIHsNCiAgICAgICAgKytxLmRpZ2l0c1tuIC0gdF07DQogICAgICAgIHIgPSBiaVN1YnRyYWN0KHIsIGIpOw0KICAgIH0NCiAgICBmb3IgKHZhciBpID0gbjsgaSA+IHQ7IC0taSkgew0KICAgICAgICB2YXIgcmkgPSAoaSA+PSByLmRpZ2l0cy5sZW5ndGgpID8gMCA6IHIuZGlnaXRzW2ldOw0KICAgICAgICB2YXIgcmkxID0gKGkgLSAxID49IHIuZGlnaXRzLmxlbmd0aCkgPyAwIDogci5kaWdpdHNbaSAtIDFdOw0KICAgICAgICB2YXIgcmkyID0gKGkgLSAyID49IHIuZGlnaXRzLmxlbmd0aCkgPyAwIDogci5kaWdpdHNbaSAtIDJdOw0KICAgICAgICB2YXIgeXQgPSAodCA+PSB5LmRpZ2l0cy5sZW5ndGgpID8gMCA6IHkuZGlnaXRzW3RdOw0KICAgICAgICB2YXIgeXQxID0gKHQgLSAxID49IHkuZGlnaXRzLmxlbmd0aCkgPyAwIDogeS5kaWdpdHNbdCAtIDFdOw0KICAgICAgICBpZiAocmkgPT0geXQpIHsNCiAgICAgICAgICAgIHEuZGlnaXRzW2kgLSB0IC0gMV0gPSBtYXhEaWdpdFZhbDsNCiAgICAgICAgfSBlbHNlIHsNCiAgICAgICAgICAgIHEuZGlnaXRzW2kgLSB0IC0gMV0gPSBNYXRoLmZsb29yKChyaSAqIGJpUmFkaXggKyByaTEpIC8geXQpOw0KICAgICAgICB9DQoNCiAgICAgICAgdmFyIGMxID0gcS5kaWdpdHNbaSAtIHQgLSAxXSAqICgoeXQgKiBiaVJhZGl4KSArIHl0MSk7DQogICAgICAgIHZhciBjMiA9IChyaSAqIGJpUmFkaXhTcXVhcmVkKSArICgocmkxICogYmlSYWRpeCkgKyByaTIpOw0KICAgICAgICB3aGlsZSAoYzEgPiBjMikgew0KICAgICAgICAgICAgLS1xLmRpZ2l0c1tpIC0gdCAtIDFdOw0KICAgICAgICAgICAgYzEgPSBxLmRpZ2l0c1tpIC0gdCAtIDFdICogKCh5dCAqIGJpUmFkaXgpIHwgeXQxKTsNCiAgICAgICAgICAgIGMyID0gKHJpICogYmlSYWRpeCAqIGJpUmFkaXgpICsgKChyaTEgKiBiaVJhZGl4KSArIHJpMik7DQogICAgICAgIH0NCg0KICAgICAgICBiID0gYmlNdWx0aXBseUJ5UmFkaXhQb3dlcih5LCBpIC0gdCAtIDEpOw0KICAgICAgICByID0gYmlTdWJ0cmFjdChyLCBiaU11bHRpcGx5RGlnaXQoYiwgcS5kaWdpdHNbaSAtIHQgLSAxXSkpOw0KICAgICAgICBpZiAoci5pc05lZykgew0KICAgICAgICAgICAgciA9IGJpQWRkKHIsIGIpOw0KICAgICAgICAgICAgLS1xLmRpZ2l0c1tpIC0gdCAtIDFdOw0KICAgICAgICB9DQogICAgfQ0KICAgIHIgPSBiaVNoaWZ0UmlnaHQociwgbGFtYmRhKTsNCiAgICAvLyBGaWRkbGUgd2l0aCB0aGUgc2lnbnMgYW5kIHN0dWZmIHRvIG1ha2Ugc3VyZSB0aGF0IDAgPD0gciA8IHkuDQogICAgcS5pc05lZyA9IHguaXNOZWcgIT0gb3JpZ1lJc05lZzsNCiAgICBpZiAoeC5pc05lZykgew0KICAgICAgICBpZiAob3JpZ1lJc05lZykgew0KICAgICAgICAgICAgcSA9IGJpQWRkKHEsIGJpZ09uZSk7DQogICAgICAgIH0gZWxzZSB7DQogICAgICAgICAgICBxID0gYmlTdWJ0cmFjdChxLCBiaWdPbmUpOw0KICAgICAgICB9DQogICAgICAgIHkgPSBiaVNoaWZ0UmlnaHQoeSwgbGFtYmRhKTsNCiAgICAgICAgciA9IGJpU3VidHJhY3QoeSwgcik7DQogICAgfQ0KICAgIC8vIENoZWNrIGZvciB0aGUgdW5iZWxpZXZhYmx5IHN0dXBpZCBkZWdlbmVyYXRlIGNhc2Ugb2YgciA9PSAtMC4NCiAgICBpZiAoci5kaWdpdHNbMF0gPT0gMCAmJiBiaUhpZ2hJbmRleChyKSA9PSAwKSByLmlzTmVnID0gZmFsc2U7DQoNCiAgICByZXR1cm4gbmV3IEFycmF5KHEsIHIpOw0KfQ0KDQpmdW5jdGlvbiBiaURpdmlkZSh4LCB5KQ0Kew0KICAgIHJldHVybiBiaURpdmlkZU1vZHVsbyh4LCB5KVswXTsNCn0NCg0KZnVuY3Rpb24gYmlNb2R1bG8oeCwgeSkNCnsNCiAgICByZXR1cm4gYmlEaXZpZGVNb2R1bG8oeCwgeSlbMV07DQp9DQoNCmZ1bmN0aW9uIGJpTXVsdGlwbHlNb2QoeCwgeSwgbSkNCnsNCiAgICByZXR1cm4gYmlNb2R1bG8oYmlNdWx0aXBseSh4LCB5KSwgbSk7DQp9DQoNCmZ1bmN0aW9uIGJpUG93KHgsIHkpDQp7DQogICAgdmFyIHJlc3VsdCA9IGJpZ09uZTsNCiAgICB2YXIgYSA9IHg7DQogICAgd2hpbGUgKHRydWUpIHsNCiAgICAgICAgaWYgKCh5ICYgMSkgIT0gMCkgcmVzdWx0ID0gYmlNdWx0aXBseShyZXN1bHQsIGEpOw0KICAgICAgICB5ID4+PSAxOw0KICAgICAgICBpZiAoeSA9PSAwKSBicmVhazsNCiAgICAgICAgYSA9IGJpTXVsdGlwbHkoYSwgYSk7DQogICAgfQ0KICAgIHJldHVybiByZXN1bHQ7DQp9DQoNCmZ1bmN0aW9uIGJpUG93TW9kKHgsIHksIG0pDQp7DQogICAgdmFyIHJlc3VsdCA9IGJpZ09uZTsNCiAgICB2YXIgYSA9IHg7DQogICAgdmFyIGsgPSB5Ow0KICAgIHdoaWxlICh0cnVlKSB7DQogICAgICAgIGlmICgoay5kaWdpdHNbMF0gJiAxKSAhPSAwKSByZXN1bHQgPSBiaU11bHRpcGx5TW9kKHJlc3VsdCwgYSwgbSk7DQogICAgICAgIGsgPSBiaVNoaWZ0UmlnaHQoaywgMSk7DQogICAgICAgIGlmIChrLmRpZ2l0c1swXSA9PSAwICYmIGJpSGlnaEluZGV4KGspID09IDApIGJyZWFrOw0KICAgICAgICBhID0gYmlNdWx0aXBseU1vZChhLCBhLCBtKTsNCiAgICB9DQogICAgcmV0dXJuIHJlc3VsdDsNCn0NCg0KDQovL0JhcnJldHRNdSwgYSBjbGFzcyBmb3IgcGVyZm9ybWluZyBCYXJyZXR0IG1vZHVsYXIgcmVkdWN0aW9uIGNvbXB1dGF0aW9ucyBpbg0KLy9KYXZhU2NyaXB0Lg0KLy8NCi8vUmVxdWlyZXMgQmlnSW50LmpzLg0KLy8NCi8vQ29weXJpZ2h0IDIwMDQtMjAwNSBEYXZpZCBTaGFwaXJvLg0KLy8NCi8vWW91IG1heSB1c2UsIHJlLXVzZSwgYWJ1c2UsIGNvcHksIGFuZCBtb2RpZnkgdGhpcyBjb2RlIHRvIHlvdXIgbGlraW5nLCBidXQNCi8vcGxlYXNlIGtlZXAgdGhpcyBoZWFkZXIuDQovLw0KLy9UaGFua3MhDQovLw0KLy9EYXZlIFNoYXBpcm8NCi8vZGF2ZUBvaGRhdmUuY29tDQoNCmZ1bmN0aW9uIEJhcnJldHRNdShtKQ0Kew0KICAgIHRoaXMubW9kdWx1cyA9IGJpQ29weShtKTsNCiAgICB0aGlzLmsgPSBiaUhpZ2hJbmRleCh0aGlzLm1vZHVsdXMpICsgMTsNCiAgICB2YXIgYjJrID0gbmV3IEJpZ0ludCgpOw0KICAgIGIyay5kaWdpdHNbMiAqIHRoaXMua10gPSAxOyAvLyBiMmsgPSBiXigyaykNCiAgICB0aGlzLm11ID0gYmlEaXZpZGUoYjJrLCB0aGlzLm1vZHVsdXMpOw0KICAgIHRoaXMuYmtwbHVzMSA9IG5ldyBCaWdJbnQoKTsNCiAgICB0aGlzLmJrcGx1czEuZGlnaXRzW3RoaXMuayArIDFdID0gMTsgLy8gYmtwbHVzMSA9IGJeKGsrMSkNCiAgICB0aGlzLm1vZHVsbyA9IEJhcnJldHRNdV9tb2R1bG87DQogICAgdGhpcy5tdWx0aXBseU1vZCA9IEJhcnJldHRNdV9tdWx0aXBseU1vZDsNCiAgICB0aGlzLnBvd01vZCA9IEJhcnJldHRNdV9wb3dNb2Q7DQp9DQoNCmZ1bmN0aW9uIEJhcnJldHRNdV9tb2R1bG8oeCkNCnsNCiAgICB2YXIgcTEgPSBiaURpdmlkZUJ5UmFkaXhQb3dlcih4LCB0aGlzLmsgLSAxKTsNCiAgICB2YXIgcTIgPSBiaU11bHRpcGx5KHExLCB0aGlzLm11KTsNCiAgICB2YXIgcTMgPSBiaURpdmlkZUJ5UmFkaXhQb3dlcihxMiwgdGhpcy5rICsgMSk7DQogICAgdmFyIHIxID0gYmlNb2R1bG9CeVJhZGl4UG93ZXIoeCwgdGhpcy5rICsgMSk7DQogICAgdmFyIHIydGVybSA9IGJpTXVsdGlwbHkocTMsIHRoaXMubW9kdWx1cyk7DQogICAgdmFyIHIyID0gYmlNb2R1bG9CeVJhZGl4UG93ZXIocjJ0ZXJtLCB0aGlzLmsgKyAxKTsNCiAgICB2YXIgciA9IGJpU3VidHJhY3QocjEsIHIyKTsNCiAgICBpZiAoci5pc05lZykgew0KICAgICAgICByID0gYmlBZGQociwgdGhpcy5ia3BsdXMxKTsNCiAgICB9DQogICAgdmFyIHJndGVtID0gYmlDb21wYXJlKHIsIHRoaXMubW9kdWx1cykgPj0gMDsNCiAgICB3aGlsZSAocmd0ZW0pIHsNCiAgICAgICAgciA9IGJpU3VidHJhY3QociwgdGhpcy5tb2R1bHVzKTsNCiAgICAgICAgcmd0ZW0gPSBiaUNvbXBhcmUociwgdGhpcy5tb2R1bHVzKSA+PSAwOw0KICAgIH0NCiAgICByZXR1cm4gcjsNCn0NCg0KZnVuY3Rpb24gQmFycmV0dE11X211bHRpcGx5TW9kKHgsIHkpDQp7DQogICAgLyoNCiAgICAgeCA9IHRoaXMubW9kdWxvKHgpOw0KICAgICB5ID0gdGhpcy5tb2R1bG8oeSk7DQogICAgICovDQogICAgdmFyIHh5ID0gYmlNdWx0aXBseSh4LCB5KTsNCiAgICByZXR1cm4gdGhpcy5tb2R1bG8oeHkpOw0KfQ0KDQpmdW5jdGlvbiBCYXJyZXR0TXVfcG93TW9kKHgsIHkpDQp7DQogICAgdmFyIHJlc3VsdCA9IG5ldyBCaWdJbnQoKTsNCiAgICByZXN1bHQuZGlnaXRzWzBdID0gMTsNCiAgICB2YXIgYSA9IHg7DQogICAgdmFyIGsgPSB5Ow0KICAgIHdoaWxlICh0cnVlKSB7DQogICAgICAgIGlmICgoay5kaWdpdHNbMF0gJiAxKSAhPSAwKSByZXN1bHQgPSB0aGlzLm11bHRpcGx5TW9kKHJlc3VsdCwgYSk7DQogICAgICAgIGsgPSBiaVNoaWZ0UmlnaHQoaywgMSk7DQogICAgICAgIGlmIChrLmRpZ2l0c1swXSA9PSAwICYmIGJpSGlnaEluZGV4KGspID09IDApIGJyZWFrOw0KICAgICAgICBhID0gdGhpcy5tdWx0aXBseU1vZChhLCBhKTsNCiAgICB9DQogICAgcmV0dXJuIHJlc3VsdDsNCn0=";

    @Override
    public HttpResult<Map<String, Object>> init(OperatorParam param) {
        HttpResult<Map<String, Object>> result = new HttpResult<>();
        try {
            return result.success();
        } catch (Exception e) {
            logger.error("登录-->初始化失败,param={}", param, e);
            return result.failure(ErrorCode.TASK_INIT_ERROR);
        }
    }

    @Override
    public HttpResult<String> refeshPicCode(OperatorParam param) {
        switch (param.getFormType()) {
            case FormType.LOGIN:
                return refeshPicCodeForLogin(param);
            case FormType.VALIDATE_BILL_DETAIL:
                return refeshPicCodeForBillDetail(param);
            default:
                return new HttpResult<String>().failure(ErrorCode.NOT_SUPORT_METHOD);
        }
    }

    @Override
    public HttpResult<Map<String, Object>> refeshSmsCode(OperatorParam param) {
        switch (param.getFormType()) {
            case FormType.VALIDATE_BILL_DETAIL:
                return refeshSmsCodeForBillDetail(param);
            default:
                return new HttpResult<Map<String, Object>>().failure(ErrorCode.NOT_SUPORT_METHOD);
        }
    }

    @Override
    public HttpResult<Map<String, Object>> submit(OperatorParam param) {
        switch (param.getFormType()) {
            case FormType.LOGIN:
                return submitForLogin(param);
            case FormType.VALIDATE_BILL_DETAIL:
                return submitForBillDetail(param);
            default:
                return new HttpResult<Map<String, Object>>().failure(ErrorCode.NOT_SUPORT_METHOD);
        }
    }

    @Override
    public HttpResult<Map<String, Object>> validatePicCode(OperatorParam param) {
        switch (param.getFormType()) {
            case FormType.VALIDATE_BILL_DETAIL:
                return validatePicCodeForBillDetail(param);
            default:
                return new HttpResult<Map<String, Object>>().failure(ErrorCode.NOT_SUPORT_METHOD);
        }
    }

    @Override
    public HttpResult<Object> defineProcess(OperatorParam param) {
        return new HttpResult<Object>().failure(ErrorCode.NOT_SUPORT_METHOD);
    }

    private HttpResult<String> refeshPicCodeForLogin(OperatorParam param) {
        HttpResult<String> result = new HttpResult<>();
        Response response = null;
        try {
            String templateUrl = "http://waphn.189.cn/page/common/login/imagelogin.jsp";
            response = TaskHttpClient.create(param.getTaskId(), param.getWebsiteName(), RequestType.GET, "hu_nan_10000_wap_001")
                    .setFullUrl(templateUrl).invoke();
            logger.info("登录-->图片验证码-->刷新成功,param={}", param);
            return result.success(response.getPageContentForBase64());
        } catch (Exception e) {
            logger.error("登录-->图片验证码-->刷新失败,param={},response={}", param, response, e);
            return result.failure(ErrorCode.REFESH_PIC_CODE_ERROR);
        }
    }

    private HttpResult<Map<String, Object>> submitForLogin(OperatorParam param) {
        CheckUtils.checkNotBlank(param.getPassword(), ErrorCode.EMPTY_PASSWORD);
        HttpResult<Map<String, Object>> result = new HttpResult<>();
        Response response = null;
        try {
            Invocable invocable_mobile = ScriptEngineUtil.createInvocableFromBase64(javaScript_mobile);
            String encryptMobile = invocable_mobile.invokeFunction("encryptStr", param.getMobile().toString()).toString();

            Invocable invocable_password = ScriptEngineUtil.createInvocableFromBase64(javaScript_password);
            String encryptPassword = invocable_password.invokeFunction("encyptPwd", param.getPassword()).toString();

            String referer = "http://waphn.189.cn/user/login/toLogin.action";
            String templateUrl = "http://waphn.189.cn/user/login/userLogin.action";
            String templateData = "loginModel=&reUrl=&phoneNum={}&servicePwd={}&accountType=2000004&areaCode=&pwdType=1&vicode={}";
            String data = TemplateUtils.format(templateData, encryptMobile, encryptPassword, param.getPicCode());
            response = TaskHttpClient.create(param, RequestType.POST, "hu_nan_10000_wap_002").setFullUrl(templateUrl).setReferer(referer)
                    .setRequestBody(data).invoke();
            String pageContent = response.getPageContent();
            if (StringUtils.contains(pageContent, "你好")) {
                logger.warn("登录成功,params={}", param);
                return result.success();
            } else {
                String errorMsg = pageContent;
                List<String> errorMessageList = XPathUtil.getXpath("//p[@id='msg_p']/text()", pageContent);
                if (CollectionUtils.isNotEmpty(errorMessageList)) {
                    errorMsg = errorMessageList.get(0);
                }
                logger.warn("登录失败,param={},errorMsg={}", param, errorMsg);
                return result.failure(ErrorCode.LOGIN_UNEXPECTED_RESULT);
            }
        } catch (Exception e) {
            logger.error("登陆失败,param={},response={}", param, response, e);
            return result.failure(ErrorCode.LOGIN_ERROR);
        }
    }

    private HttpResult<String> refeshPicCodeForBillDetail(OperatorParam param) {
        HttpResult<String> result = new HttpResult<>();
        Response response = null;
        try {
            String templateUrl = "http://waphn.189.cn/page/common/image.jsp?t={}";
            response = TaskHttpClient.create(param.getTaskId(), param.getWebsiteName(), RequestType.GET, "hu_nan_10000_wap_003")
                    .setFullUrl(templateUrl, System.currentTimeMillis()).invoke();
            logger.info("详单-->图片验证码-->刷新成功,param={}", param);
            return result.success(response.getPageContentForBase64());
        } catch (Exception e) {
            logger.error("详单-->图片验证码-->刷新失败,param={},response={}", param, response, e);
            return result.failure(ErrorCode.REFESH_PIC_CODE_ERROR);
        }
    }

    private HttpResult<Map<String, Object>> validatePicCodeForBillDetail(OperatorParam param) {
        CheckUtils.checkNotBlank(param.getPicCode(), ErrorCode.EMPTY_PIC_CODE);
        HttpResult<Map<String, Object>> result = new HttpResult<>();
        Response response = null;
        try {
            String templateUrl = "http://waphn.189.cn/hnselfservice/billquery/queryBilly.action?number={}&vicode={}";
            response = TaskHttpClient.create(param, RequestType.GET, "hu_nan_10000_wap_004")
                    .setFullUrl(templateUrl, param.getMobile(), param.getPicCode()).invoke();
            if (StringUtils.contains(response.getPageContent(), "success")) {
                logger.info("详单-->图片验证码-->校验成功,param={}", param);
                return result.success();
            } else {
                logger.error("详单-->图片验证码-->校验失败,param={},pageContent={}", param, response.getPageContent());
                return result.failure(ErrorCode.VALIDATE_PIC_CODE_UNEXPECTED_RESULT);
            }
        } catch (Exception e) {
            logger.error("详单-->图片验证码-->校验失败,param={},response={}", param, response, e);
            return result.failure(ErrorCode.VALIDATE_PIC_CODE_ERROR);
        }
    }

    private HttpResult<Map<String, Object>> refeshSmsCodeForBillDetail(OperatorParam param) {
        HttpResult<Map<String, Object>> result = new HttpResult<>();
        try {
            logger.info("详单-->短信验证码-->刷新成功,param={}", param);
            return result.success();
        } catch (Exception e) {
            logger.error("详单-->短信验证码-->刷新失败,param={}", param, e);
            return result.failure(ErrorCode.REFESH_SMS_ERROR);
        }
    }

    private HttpResult<Map<String, Object>> submitForBillDetail(OperatorParam param) {
        CheckUtils.checkNotBlank(param.getSmsCode(), ErrorCode.EMPTY_SMS_CODE);
        HttpResult<Map<String, Object>> result = new HttpResult<>();
        Response response = null;
        try {
            String queryMonth = new DateTime().toString("yyyy-MM");
            String lastMonth = new DateTime().withFieldAdded(DurationFieldType.months(), -1).toString("yyyy-MM");

            String referer = "http://waphn.189.cn/hnselfservice/billquery/queryBillList.action?patitype=2";
            String templateUrl = "http://waphn.189.cn/hnselfservice/billquery/queryBillListx" +
                    ".action?tm=&tabIndex=2&queryMonth={}&patitype=2&code={}&accNbr={}&chargeType=";
            response = TaskHttpClient.create(param, RequestType.GET, "hu_nan_10000_wap_005")
                    .setFullUrl(templateUrl, queryMonth, param.getSmsCode(), param.getMobile()).setReferer(referer).invoke();
            if (StringUtils.contains(response.getPageContent(), "客户号码")) {
                logger.info("详单-->校验成功,param={}", param);
                return result.success();
            } else {
                response = TaskHttpClient.create(param, RequestType.GET, "hu_nan_10000_wap_006")
                        .setFullUrl(templateUrl, lastMonth, param.getSmsCode(), param.getMobile()).setReferer(referer).invoke();
                if (StringUtils.contains(response.getPageContent(), "客户号码")) {
                    logger.info("详单-->校验成功,param={}", param);
                    return result.success();
                } else {
                    logger.error("详单-->校验失败,param={},pageContent={}", param, response.getPageContent());
                    return result.failure(ErrorCode.VALIDATE_UNEXPECTED_RESULT);
                }
            }
        } catch (Exception e) {
            logger.error("详单-->校验失败,param={},response={}", param, response, e);
            return result.failure(ErrorCode.VALIDATE_ERROR);
        }
    }
}
