/**
 * This document and its contents are protected by copyright 2005 and owned by datatrees.com Inc. The
 * copying and reproduction of this document and/or its content (whether wholly or partly) or any
 * incorporation of the same into any other material in any media or format of any kind is strictly
 * prohibited. All rights are reserved.
 * 
 * Copyright (c) datatrees.com Inc. 2015
 */
package com.datatrees.common.protocol.http;

import java.util.List;

/**
 * The base level of services required for Http Authentication
 * 
 * @see HttpAuthenticationFactory
 * 
 * @author Matt Tencati
 */
public interface HttpAuthentication {

    /**
     * Gets the credentials generated by the HttpAuthentication object. May return null.
     * 
     * @return The credentials value
     */
    public List getCredentials();

    /**
     * Gets the realm used by the HttpAuthentication object during creation.
     * 
     * @return The realm value
     */
    public String getRealm();

}
