package com.datatrees.rawdatacentral.api.model;

public enum StatusCode {
    SMSCODE("REFRESH_LOGIN_RANDOMPASSWORD"), PICCODE("REFRESH_LOGIN_CODE"), QRLOGINCODE("REFRESH_LOGIN_QR_CODE"), NMLogin("START_LOGIN"), QRLOGIN(
            "VERIFY_LOGIN_QR_CODE"), QRCODE("VERIFY_QR_CODE"), SENDRESULT("SEND_CAPTCHA"), CRAWLERSUCCESS("SUCCESS"), CRAWLERFAIL("FAIL"), WAITSMS(
            "WAITING_FOR_SMS_VERIFY"), WAITPIC("WAITING_FOR_PICTURE_VERIFY"), WAITQR("WAITING_FOR_QR_VERIFY"), WAITLOGIN("WAITING_FOR_LOGIN"), QRCONFIRM(
            "QR_CODE_CONFIRMED"), LOGINSUCCESS("LOGIN_SUCCESS"), LOGINFAIL("LOGIN_FAILED"), PREPARECRAWL("PREPARE_FOR_CRAWL"), QRFAIL(
            "VERIFY_QR_FAILED"), QRSUCCESS("VERIFY_QR_SUCCESS");

    private String status;

    StatusCode(String status) {
        this.status = status;
    }

    public String getStaus() {
        return status;
    }
}
