package com.datatrees.rawdatacentral.plugin.operator.an_hui_10000_web;

import javax.script.Invocable;
import java.io.ByteArrayInputStream;
import java.net.URLEncoder;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Map;

import com.datatrees.common.util.GsonUtils;
import com.datatrees.common.util.PatternUtils;
import com.datatrees.crawler.core.processor.plugin.PluginConstants;
import com.datatrees.rawdatacentral.common.http.TaskHttpClient;
import com.datatrees.rawdatacentral.common.http.TaskUtils;
import com.datatrees.rawdatacentral.common.utils.CheckUtils;
import com.datatrees.rawdatacentral.common.utils.ScriptEngineUtil;
import com.datatrees.rawdatacentral.common.utils.TemplateUtils;
import com.datatrees.rawdatacentral.domain.constant.FormType;
import com.datatrees.rawdatacentral.domain.enums.ErrorCode;
import com.datatrees.rawdatacentral.domain.enums.RequestType;
import com.datatrees.rawdatacentral.domain.operator.OperatorParam;
import com.datatrees.rawdatacentral.domain.result.HttpResult;
import com.datatrees.rawdatacentral.domain.vo.Response;
import com.datatrees.rawdatacentral.service.OperatorPluginService;
import com.google.gson.reflect.TypeToken;
import com.ibm.icu.text.SimpleDateFormat;
import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * 安徽电信web端
 * 登录 手机号 服务密码 图片验证码
 * 查询详单 短信验证码
 * User: yand
 * Date: 2017/9/25
 */
public class AnHui10000ForWeb implements OperatorPluginService {

    private static       Logger logger     = LoggerFactory.getLogger(AnHui10000ForWeb.class);
    private static final String javaScript = "Ly8gQmlnSW50LCBhIHN1aXRlIG9mIHJvdXRpbmVzIGZvciBwZXJmb3JtaW5nIG11bHRpcGxlLXByZWNpc2lvbiBhcml0aG1ldGljIGluDQovLyBKYXZhU2NyaXB0Lg0KLy8NCi8vIENvcHlyaWdodCAxOTk4LTIwMDUgRGF2aWQgU2hhcGlyby4NCi8vDQovLyBZb3UgbWF5IHVzZSwgcmUtdXNlLCBhYnVzZSwNCi8vIGNvcHksIGFuZCBtb2RpZnkgdGhpcyBjb2RlIHRvIHlvdXIgbGlraW5nLCBidXQgcGxlYXNlIGtlZXAgdGhpcyBoZWFkZXIuDQovLyBUaGFua3MhDQovLw0KLy8gRGF2ZSBTaGFwaXJvDQovLyBkYXZlQG9oZGF2ZS5jb20NCg0KLy8gSU1QT1JUQU5UIFRISU5HOiBCZSBzdXJlIHRvIHNldCBtYXhEaWdpdHMgYWNjb3JkaW5nIHRvIHlvdXIgcHJlY2lzaW9uDQovLyBuZWVkcy4gVXNlIHRoZSBzZXRNYXhEaWdpdHMoKSBmdW5jdGlvbiB0byBkbyB0aGlzLiBTZWUgY29tbWVudHMgYmVsb3cuDQovLw0KLy8gVHdlYWtlZCBieSBJYW4gQnVubmluZw0KLy8gQWx0ZXJhdGlvbnM6DQovLyBGaXggYnVnIGluIGZ1bmN0aW9uIGJpRnJvbUhleChzKSB0byBhbGxvdw0KLy8gcGFyc2luZyBvZiBzdHJpbmdzIG9mIGxlbmd0aCAhPSAwIChtb2QgNCkNCg0KLy8gQ2hhbmdlcyBtYWRlIGJ5IERhdmUgU2hhcGlybyBhcyBvZiAxMi8zMC8yMDA0Og0KLy8NCi8vIFRoZSBCaWdJbnQoKSBjb25zdHJ1Y3RvciBkb2Vzbid0IHRha2UgYSBzdHJpbmcgYW55bW9yZS4gSWYgeW91IHdhbnQgdG8NCi8vIGNyZWF0ZSBhIEJpZ0ludCBmcm9tIGEgc3RyaW5nLCB1c2UgYmlGcm9tRGVjaW1hbCgpIGZvciBiYXNlLTEwDQovLyByZXByZXNlbnRhdGlvbnMsIGJpRnJvbUhleCgpIGZvciBiYXNlLTE2IHJlcHJlc2VudGF0aW9ucywgb3INCi8vIGJpRnJvbVN0cmluZygpIGZvciBiYXNlLTItdG8tMzYgcmVwcmVzZW50YXRpb25zLg0KLy8NCi8vIGJpRnJvbUFycmF5KCkgaGFzIGJlZW4gcmVtb3ZlZC4gVXNlIGJpQ29weSgpIGluc3RlYWQsIHBhc3NpbmcgYSBCaWdJbnQNCi8vIGluc3RlYWQgb2YgYW4gYXJyYXkuDQovLw0KLy8gVGhlIEJpZ0ludCgpIGNvbnN0cnVjdG9yIG5vdyBvbmx5IGNvbnN0cnVjdHMgYSB6ZXJvZWQtb3V0IGFycmF5Lg0KLy8gQWx0ZXJuYXRpdmVseSwgaWYgeW91IHBhc3MgPHRydWU+LCBpdCB3b24ndCBjb25zdHJ1Y3QgYW55IGFycmF5LiBTZWUgdGhlDQovLyBiaUNvcHkoKSBtZXRob2QgZm9yIGFuIGV4YW1wbGUgb2YgdGhpcy4NCi8vDQovLyBCZSBzdXJlIHRvIHNldCBtYXhEaWdpdHMgZGVwZW5kaW5nIG9uIHlvdXIgcHJlY2lzaW9uIG5lZWRzLiBUaGUgZGVmYXVsdA0KLy8gemVyb2VkLW91dCBhcnJheSBaRVJPX0FSUkFZIGlzIGNvbnN0cnVjdGVkIGluc2lkZSB0aGUgc2V0TWF4RGlnaXRzKCkNCi8vIGZ1bmN0aW9uLiBTbyB1c2UgdGhpcyBmdW5jdGlvbiB0byBzZXQgdGhlIHZhcmlhYmxlLiBET04nVCBKVVNUIFNFVCBUSEUNCi8vIFZBTFVFLiBVU0UgVEhFIEZVTkNUSU9OLg0KLy8NCi8vIFpFUk9fQVJSQVkgZXhpc3RzIHRvIGhvcGVmdWxseSBzcGVlZCB1cCBjb25zdHJ1Y3Rpb24gb2YgQmlnSW50cygpLiBCeQ0KLy8gcHJlY2FsY3VsYXRpbmcgdGhlIHplcm8gYXJyYXksIHdlIGNhbiBqdXN0IHVzZSBzbGljZSgwKSB0byBtYWtlIGNvcGllcyBvZg0KLy8gaXQuIFByZXN1bWFibHkgdGhpcyBjYWxscyBmYXN0ZXIgbmF0aXZlIGNvZGUsIGFzIG9wcG9zZWQgdG8gc2V0dGluZyB0aGUNCi8vIGVsZW1lbnRzIG9uZSBhdCBhIHRpbWUuIEkgaGF2ZSBub3QgZG9uZSBhbnkgdGltaW5nIHRlc3RzIHRvIHZlcmlmeSB0aGlzDQovLyBjbGFpbS4NCg0KLy8gTWF4IG51bWJlciA9IDEwXjE2IC0gMiA9IDk5OTk5OTk5OTk5OTk5OTg7DQovLyAgICAgICAgICAgICAgIDJeNTMgICAgID0gOTAwNzE5OTI1NDc0MDk5MjsNCg0KdmFyIGJpUmFkaXhCYXNlID0gMjsNCnZhciBiaVJhZGl4Qml0cyA9IDE2Ow0KdmFyIGJpdHNQZXJEaWdpdCA9IGJpUmFkaXhCaXRzOw0KdmFyIGJpUmFkaXggPSAxIDw8IDE2OyAvLyA9IDJeMTYgPSA2NTUzNg0KdmFyIGJpSGFsZlJhZGl4ID0gYmlSYWRpeCA+Pj4gMTsNCnZhciBiaVJhZGl4U3F1YXJlZCA9IGJpUmFkaXggKiBiaVJhZGl4Ow0KdmFyIG1heERpZ2l0VmFsID0gYmlSYWRpeCAtIDE7DQp2YXIgbWF4SW50ZWdlciA9IDk5OTk5OTk5OTk5OTk5OTg7DQoNCi8vIG1heERpZ2l0czoNCi8vIENoYW5nZSB0aGlzIHRvIGFjY29tbW9kYXRlIHlvdXIgbGFyZ2VzdCBudW1iZXIgc2l6ZS4gVXNlIHNldE1heERpZ2l0cygpDQovLyB0byBjaGFuZ2UgaXQhDQovLw0KLy8gSW4gZ2VuZXJhbCwgaWYgeW91J3JlIHdvcmtpbmcgd2l0aCBudW1iZXJzIG9mIHNpemUgTiBiaXRzLCB5b3UnbGwgbmVlZCAyKk4NCi8vIGJpdHMgb2Ygc3RvcmFnZS4gRWFjaCBkaWdpdCBob2xkcyAxNiBiaXRzLiBTbywgYSAxMDI0LWJpdCBrZXkgd2lsbCBuZWVkDQovLw0KLy8gMTAyNCAqIDIgLyAxNiA9IDEyOCBkaWdpdHMgb2Ygc3RvcmFnZS4NCi8vDQoNCnZhciBtYXhEaWdpdHM7DQp2YXIgWkVST19BUlJBWTsNCnZhciBiaWdaZXJvLCBiaWdPbmU7DQoNCmZ1bmN0aW9uIHNldE1heERpZ2l0cyh2YWx1ZSkNCnsNCiAgICBtYXhEaWdpdHMgPSB2YWx1ZTsNCiAgICBaRVJPX0FSUkFZID0gbmV3IEFycmF5KG1heERpZ2l0cyk7DQogICAgZm9yICh2YXIgaXphID0gMDsgaXphIDwgWkVST19BUlJBWS5sZW5ndGg7IGl6YSsrKSBaRVJPX0FSUkFZW2l6YV0gPSAwOw0KICAgIGJpZ1plcm8gPSBuZXcgQmlnSW50KCk7DQogICAgYmlnT25lID0gbmV3IEJpZ0ludCgpOw0KICAgIGJpZ09uZS5kaWdpdHNbMF0gPSAxOw0KfQ0KDQpzZXRNYXhEaWdpdHMoMTI5KTsNCg0KLy8gVGhlIG1heGltdW0gbnVtYmVyIG9mIGRpZ2l0cyBpbiBiYXNlIDEwIHlvdSBjYW4gY29udmVydCB0byBhbg0KLy8gaW50ZWdlciB3aXRob3V0IEphdmFTY3JpcHQgdGhyb3dpbmcgdXAgb24geW91Lg0KdmFyIGRwbDEwID0gMTU7DQovLyBscjEwID0gMTAgXiBkcGwxMA0KdmFyIGxyMTAgPSBiaUZyb21OdW1iZXIoMTAwMDAwMDAwMDAwMDAwMCk7DQoNCmZ1bmN0aW9uIEJpZ0ludChmbGFnKQ0Kew0KICAgIGlmICh0eXBlb2YgZmxhZyA9PSAiYm9vbGVhbiIgJiYgZmxhZyA9PSB0cnVlKSB7DQogICAgICAgIHRoaXMuZGlnaXRzID0gbnVsbDsNCiAgICB9DQogICAgZWxzZSB7DQogICAgICAgIHRoaXMuZGlnaXRzID0gWkVST19BUlJBWS5zbGljZSgwKTsNCiAgICB9DQogICAgdGhpcy5pc05lZyA9IGZhbHNlOw0KfQ0KDQpmdW5jdGlvbiBiaUZyb21EZWNpbWFsKHMpDQp7DQogICAgdmFyIGlzTmVnID0gcy5jaGFyQXQoMCkgPT0gJy0nOw0KICAgIHZhciBpID0gaXNOZWcgPyAxIDogMDsNCiAgICB2YXIgcmVzdWx0Ow0KICAgIC8vIFNraXAgbGVhZGluZyB6ZXJvcy4NCiAgICB3aGlsZSAoaSA8IHMubGVuZ3RoICYmIHMuY2hhckF0KGkpID09ICcwJykgKytpOw0KICAgIGlmIChpID09IHMubGVuZ3RoKSB7DQogICAgICAgIHJlc3VsdCA9IG5ldyBCaWdJbnQoKTsNCiAgICB9DQogICAgZWxzZSB7DQogICAgICAgIHZhciBkaWdpdENvdW50ID0gcy5sZW5ndGggLSBpOw0KICAgICAgICB2YXIgZmdsID0gZGlnaXRDb3VudCAlIGRwbDEwOw0KICAgICAgICBpZiAoZmdsID09IDApIGZnbCA9IGRwbDEwOw0KICAgICAgICByZXN1bHQgPSBiaUZyb21OdW1iZXIoTnVtYmVyKHMuc3Vic3RyKGksIGZnbCkpKTsNCiAgICAgICAgaSArPSBmZ2w7DQogICAgICAgIHdoaWxlIChpIDwgcy5sZW5ndGgpIHsNCiAgICAgICAgICAgIHJlc3VsdCA9IGJpQWRkKGJpTXVsdGlwbHkocmVzdWx0LCBscjEwKSwNCiAgICAgICAgICAgICAgICBiaUZyb21OdW1iZXIoTnVtYmVyKHMuc3Vic3RyKGksIGRwbDEwKSkpKTsNCiAgICAgICAgICAgIGkgKz0gZHBsMTA7DQogICAgICAgIH0NCiAgICAgICAgcmVzdWx0LmlzTmVnID0gaXNOZWc7DQogICAgfQ0KICAgIHJldHVybiByZXN1bHQ7DQp9DQoNCmZ1bmN0aW9uIGJpQ29weShiaSkNCnsNCiAgICB2YXIgcmVzdWx0ID0gbmV3IEJpZ0ludCh0cnVlKTsNCiAgICByZXN1bHQuZGlnaXRzID0gYmkuZGlnaXRzLnNsaWNlKDApOw0KICAgIHJlc3VsdC5pc05lZyA9IGJpLmlzTmVnOw0KICAgIHJldHVybiByZXN1bHQ7DQp9DQoNCmZ1bmN0aW9uIGJpRnJvbU51bWJlcihpKQ0Kew0KICAgIHZhciByZXN1bHQgPSBuZXcgQmlnSW50KCk7DQogICAgcmVzdWx0LmlzTmVnID0gaSA8IDA7DQogICAgaSA9IE1hdGguYWJzKGkpOw0KICAgIHZhciBqID0gMDsNCiAgICB3aGlsZSAoaSA+IDApIHsNCiAgICAgICAgcmVzdWx0LmRpZ2l0c1tqKytdID0gaSAmIG1heERpZ2l0VmFsOw0KICAgICAgICBpID0gTWF0aC5mbG9vcihpIC8gYmlSYWRpeCk7DQogICAgfQ0KICAgIHJldHVybiByZXN1bHQ7DQp9DQoNCmZ1bmN0aW9uIHJldmVyc2VTdHIocykNCnsNCiAgICB2YXIgcmVzdWx0ID0gIiI7DQogICAgZm9yICh2YXIgaSA9IHMubGVuZ3RoIC0gMTsgaSA+IC0xOyAtLWkpIHsNCiAgICAgICAgcmVzdWx0ICs9IHMuY2hhckF0KGkpOw0KICAgIH0NCiAgICByZXR1cm4gcmVzdWx0Ow0KfQ0KDQp2YXIgaGV4YXRyaWdlc2ltYWxUb0NoYXIgPSBuZXcgQXJyYXkoDQogICAgJzAnLCAnMScsICcyJywgJzMnLCAnNCcsICc1JywgJzYnLCAnNycsICc4JywgJzknLA0KICAgICdhJywgJ2InLCAnYycsICdkJywgJ2UnLCAnZicsICdnJywgJ2gnLCAnaScsICdqJywNCiAgICAnaycsICdsJywgJ20nLCAnbicsICdvJywgJ3AnLCAncScsICdyJywgJ3MnLCAndCcsDQogICAgJ3UnLCAndicsICd3JywgJ3gnLCAneScsICd6Jw0KKTsNCg0KZnVuY3Rpb24gYmlUb1N0cmluZyh4LCByYWRpeCkNCi8vIDIgPD0gcmFkaXggPD0gMzYNCnsNCiAgICB2YXIgYiA9IG5ldyBCaWdJbnQoKTsNCiAgICBiLmRpZ2l0c1swXSA9IHJhZGl4Ow0KICAgIHZhciBxciA9IGJpRGl2aWRlTW9kdWxvKHgsIGIpOw0KICAgIHZhciByZXN1bHQgPSBoZXhhdHJpZ2VzaW1hbFRvQ2hhcltxclsxXS5kaWdpdHNbMF1dOw0KICAgIHdoaWxlIChiaUNvbXBhcmUocXJbMF0sIGJpZ1plcm8pID09IDEpIHsNCiAgICAgICAgcXIgPSBiaURpdmlkZU1vZHVsbyhxclswXSwgYik7DQogICAgICAgIGRpZ2l0ID0gcXJbMV0uZGlnaXRzWzBdOw0KICAgICAgICByZXN1bHQgKz0gaGV4YXRyaWdlc2ltYWxUb0NoYXJbcXJbMV0uZGlnaXRzWzBdXTsNCiAgICB9DQogICAgcmV0dXJuICh4LmlzTmVnID8gIi0iIDogIiIpICsgcmV2ZXJzZVN0cihyZXN1bHQpOw0KfQ0KDQpmdW5jdGlvbiBiaVRvRGVjaW1hbCh4KQ0Kew0KICAgIHZhciBiID0gbmV3IEJpZ0ludCgpOw0KICAgIGIuZGlnaXRzWzBdID0gMTA7DQogICAgdmFyIHFyID0gYmlEaXZpZGVNb2R1bG8oeCwgYik7DQogICAgdmFyIHJlc3VsdCA9IFN0cmluZyhxclsxXS5kaWdpdHNbMF0pOw0KICAgIHdoaWxlIChiaUNvbXBhcmUocXJbMF0sIGJpZ1plcm8pID09IDEpIHsNCiAgICAgICAgcXIgPSBiaURpdmlkZU1vZHVsbyhxclswXSwgYik7DQogICAgICAgIHJlc3VsdCArPSBTdHJpbmcocXJbMV0uZGlnaXRzWzBdKTsNCiAgICB9DQogICAgcmV0dXJuICh4LmlzTmVnID8gIi0iIDogIiIpICsgcmV2ZXJzZVN0cihyZXN1bHQpOw0KfQ0KDQp2YXIgaGV4VG9DaGFyID0gbmV3IEFycmF5KCcwJywgJzEnLCAnMicsICczJywgJzQnLCAnNScsICc2JywgJzcnLCAnOCcsICc5JywNCiAgICAnYScsICdiJywgJ2MnLCAnZCcsICdlJywgJ2YnKTsNCg0KZnVuY3Rpb24gZGlnaXRUb0hleChuKQ0Kew0KICAgIHZhciBtYXNrID0gMHhmOw0KICAgIHZhciByZXN1bHQgPSAiIjsNCiAgICBmb3IgKGkgPSAwOyBpIDwgNDsgKytpKSB7DQogICAgICAgIHJlc3VsdCArPSBoZXhUb0NoYXJbbiAmIG1hc2tdOw0KICAgICAgICBuID4+Pj0gNDsNCiAgICB9DQogICAgcmV0dXJuIHJldmVyc2VTdHIocmVzdWx0KTsNCn0NCg0KZnVuY3Rpb24gYmlUb0hleCh4KQ0Kew0KICAgIHZhciByZXN1bHQgPSAiIjsNCiAgICB2YXIgbiA9IGJpSGlnaEluZGV4KHgpOw0KICAgIGZvciAodmFyIGkgPSBiaUhpZ2hJbmRleCh4KTsgaSA+IC0xOyAtLWkpIHsNCiAgICAgICAgcmVzdWx0ICs9IGRpZ2l0VG9IZXgoeC5kaWdpdHNbaV0pOw0KICAgIH0NCiAgICByZXR1cm4gcmVzdWx0Ow0KfQ0KDQpmdW5jdGlvbiBjaGFyVG9IZXgoYykNCnsNCiAgICB2YXIgWkVSTyA9IDQ4Ow0KICAgIHZhciBOSU5FID0gWkVSTyArIDk7DQogICAgdmFyIGxpdHRsZUEgPSA5NzsNCiAgICB2YXIgbGl0dGxlWiA9IGxpdHRsZUEgKyAyNTsNCiAgICB2YXIgYmlnQSA9IDY1Ow0KICAgIHZhciBiaWdaID0gNjUgKyAyNTsNCiAgICB2YXIgcmVzdWx0Ow0KDQogICAgaWYgKGMgPj0gWkVSTyAmJiBjIDw9IE5JTkUpIHsNCiAgICAgICAgcmVzdWx0ID0gYyAtIFpFUk87DQogICAgfSBlbHNlIGlmIChjID49IGJpZ0EgJiYgYyA8PSBiaWdaKSB7DQogICAgICAgIHJlc3VsdCA9IDEwICsgYyAtIGJpZ0E7DQogICAgfSBlbHNlIGlmIChjID49IGxpdHRsZUEgJiYgYyA8PSBsaXR0bGVaKSB7DQogICAgICAgIHJlc3VsdCA9IDEwICsgYyAtIGxpdHRsZUE7DQogICAgfSBlbHNlIHsNCiAgICAgICAgcmVzdWx0ID0gMDsNCiAgICB9DQogICAgcmV0dXJuIHJlc3VsdDsNCn0NCg0KZnVuY3Rpb24gaGV4VG9EaWdpdChzKQ0Kew0KICAgIHZhciByZXN1bHQgPSAwOw0KICAgIHZhciBzbCA9IE1hdGgubWluKHMubGVuZ3RoLCA0KTsNCiAgICBmb3IgKHZhciBpID0gMDsgaSA8IHNsOyArK2kpIHsNCiAgICAgICAgcmVzdWx0IDw8PSA0Ow0KICAgICAgICByZXN1bHQgfD0gY2hhclRvSGV4KHMuY2hhckNvZGVBdChpKSkNCiAgICB9DQogICAgcmV0dXJuIHJlc3VsdDsNCn0NCg0KZnVuY3Rpb24gYmlGcm9tSGV4KHMpDQp7DQogICAgdmFyIHJlc3VsdCA9IG5ldyBCaWdJbnQoKTsNCiAgICB2YXIgc2wgPSBzLmxlbmd0aDsNCiAgICBmb3IgKHZhciBpID0gc2wsIGogPSAwOyBpID4gMDsgaSAtPSA0LCArK2opIHsNCiAgICAgICAgcmVzdWx0LmRpZ2l0c1tqXSA9IGhleFRvRGlnaXQocy5zdWJzdHIoTWF0aC5tYXgoaSAtIDQsIDApLCBNYXRoLm1pbihpLCA0KSkpOw0KICAgIH0NCiAgICByZXR1cm4gcmVzdWx0Ow0KfQ0KDQpmdW5jdGlvbiBiaUZyb21TdHJpbmcocywgcmFkaXgpDQp7DQogICAgdmFyIGlzTmVnID0gcy5jaGFyQXQoMCkgPT0gJy0nOw0KICAgIHZhciBpc3RvcCA9IGlzTmVnID8gMSA6IDA7DQogICAgdmFyIHJlc3VsdCA9IG5ldyBCaWdJbnQoKTsNCiAgICB2YXIgcGxhY2UgPSBuZXcgQmlnSW50KCk7DQogICAgcGxhY2UuZGlnaXRzWzBdID0gMTsgLy8gcmFkaXheMA0KICAgIGZvciAodmFyIGkgPSBzLmxlbmd0aCAtIDE7IGkgPj0gaXN0b3A7IGktLSkgew0KICAgICAgICB2YXIgYyA9IHMuY2hhckNvZGVBdChpKTsNCiAgICAgICAgdmFyIGRpZ2l0ID0gY2hhclRvSGV4KGMpOw0KICAgICAgICB2YXIgYmlEaWdpdCA9IGJpTXVsdGlwbHlEaWdpdChwbGFjZSwgZGlnaXQpOw0KICAgICAgICByZXN1bHQgPSBiaUFkZChyZXN1bHQsIGJpRGlnaXQpOw0KICAgICAgICBwbGFjZSA9IGJpTXVsdGlwbHlEaWdpdChwbGFjZSwgcmFkaXgpOw0KICAgIH0NCiAgICByZXN1bHQuaXNOZWcgPSBpc05lZzsNCiAgICByZXR1cm4gcmVzdWx0Ow0KfQ0KDQpmdW5jdGlvbiBiaUR1bXAoYikNCnsNCiAgICByZXR1cm4gKGIuaXNOZWcgPyAiLSIgOiAiIikgKyBiLmRpZ2l0cy5qb2luKCIgIik7DQp9DQoNCmZ1bmN0aW9uIGJpQWRkKHgsIHkpDQp7DQogICAgdmFyIHJlc3VsdDsNCg0KICAgIGlmICh4LmlzTmVnICE9IHkuaXNOZWcpIHsNCiAgICAgICAgeS5pc05lZyA9ICF5LmlzTmVnOw0KICAgICAgICByZXN1bHQgPSBiaVN1YnRyYWN0KHgsIHkpOw0KICAgICAgICB5LmlzTmVnID0gIXkuaXNOZWc7DQogICAgfQ0KICAgIGVsc2Ugew0KICAgICAgICByZXN1bHQgPSBuZXcgQmlnSW50KCk7DQogICAgICAgIHZhciBjID0gMDsNCiAgICAgICAgdmFyIG47DQogICAgICAgIGZvciAodmFyIGkgPSAwOyBpIDwgeC5kaWdpdHMubGVuZ3RoOyArK2kpIHsNCiAgICAgICAgICAgIG4gPSB4LmRpZ2l0c1tpXSArIHkuZGlnaXRzW2ldICsgYzsNCiAgICAgICAgICAgIHJlc3VsdC5kaWdpdHNbaV0gPSBuICUgYmlSYWRpeDsNCiAgICAgICAgICAgIGMgPSBOdW1iZXIobiA+PSBiaVJhZGl4KTsNCiAgICAgICAgfQ0KICAgICAgICByZXN1bHQuaXNOZWcgPSB4LmlzTmVnOw0KICAgIH0NCiAgICByZXR1cm4gcmVzdWx0Ow0KfQ0KDQpmdW5jdGlvbiBiaVN1YnRyYWN0KHgsIHkpDQp7DQogICAgdmFyIHJlc3VsdDsNCiAgICBpZiAoeC5pc05lZyAhPSB5LmlzTmVnKSB7DQogICAgICAgIHkuaXNOZWcgPSAheS5pc05lZzsNCiAgICAgICAgcmVzdWx0ID0gYmlBZGQoeCwgeSk7DQogICAgICAgIHkuaXNOZWcgPSAheS5pc05lZzsNCiAgICB9IGVsc2Ugew0KICAgICAgICByZXN1bHQgPSBuZXcgQmlnSW50KCk7DQogICAgICAgIHZhciBuLCBjOw0KICAgICAgICBjID0gMDsNCiAgICAgICAgZm9yICh2YXIgaSA9IDA7IGkgPCB4LmRpZ2l0cy5sZW5ndGg7ICsraSkgew0KICAgICAgICAgICAgbiA9IHguZGlnaXRzW2ldIC0geS5kaWdpdHNbaV0gKyBjOw0KICAgICAgICAgICAgcmVzdWx0LmRpZ2l0c1tpXSA9IG4gJSBiaVJhZGl4Ow0KICAgICAgICAgICAgLy8gU3R1cGlkIG5vbi1jb25mb3JtaW5nIG1vZHVsdXMgb3BlcmF0aW9uLg0KICAgICAgICAgICAgaWYgKHJlc3VsdC5kaWdpdHNbaV0gPCAwKSByZXN1bHQuZGlnaXRzW2ldICs9IGJpUmFkaXg7DQogICAgICAgICAgICBjID0gMCAtIE51bWJlcihuIDwgMCk7DQogICAgICAgIH0NCiAgICAgICAgLy8gRml4IHVwIHRoZSBuZWdhdGl2ZSBzaWduLCBpZiBhbnkuDQogICAgICAgIGlmIChjID09IC0xKSB7DQogICAgICAgICAgICBjID0gMDsNCiAgICAgICAgICAgIGZvciAodmFyIGkgPSAwOyBpIDwgeC5kaWdpdHMubGVuZ3RoOyArK2kpIHsNCiAgICAgICAgICAgICAgICBuID0gMCAtIHJlc3VsdC5kaWdpdHNbaV0gKyBjOw0KICAgICAgICAgICAgICAgIHJlc3VsdC5kaWdpdHNbaV0gPSBuICUgYmlSYWRpeDsNCiAgICAgICAgICAgICAgICAvLyBTdHVwaWQgbm9uLWNvbmZvcm1pbmcgbW9kdWx1cyBvcGVyYXRpb24uDQogICAgICAgICAgICAgICAgaWYgKHJlc3VsdC5kaWdpdHNbaV0gPCAwKSByZXN1bHQuZGlnaXRzW2ldICs9IGJpUmFkaXg7DQogICAgICAgICAgICAgICAgYyA9IDAgLSBOdW1iZXIobiA8IDApOw0KICAgICAgICAgICAgfQ0KICAgICAgICAgICAgLy8gUmVzdWx0IGlzIG9wcG9zaXRlIHNpZ24gb2YgYXJndW1lbnRzLg0KICAgICAgICAgICAgcmVzdWx0LmlzTmVnID0gIXguaXNOZWc7DQogICAgICAgIH0gZWxzZSB7DQogICAgICAgICAgICAvLyBSZXN1bHQgaXMgc2FtZSBzaWduLg0KICAgICAgICAgICAgcmVzdWx0LmlzTmVnID0geC5pc05lZzsNCiAgICAgICAgfQ0KICAgIH0NCiAgICByZXR1cm4gcmVzdWx0Ow0KfQ0KDQoNCmZ1bmN0aW9uIGJpSGlnaEluZGV4KHgpDQp7DQogICAgdmFyIHJlc3VsdCA9IHguZGlnaXRzLmxlbmd0aCAtIDE7DQogICAgd2hpbGUgKHJlc3VsdCA+IDAgJiYgeC5kaWdpdHNbcmVzdWx0XSA9PSAwKSAtLXJlc3VsdDsNCiAgICByZXR1cm4gcmVzdWx0Ow0KfQ0KDQpmdW5jdGlvbiBiaU51bUJpdHMoeCkNCnsNCiAgICB2YXIgbiA9IGJpSGlnaEluZGV4KHgpOw0KICAgIHZhciBkID0geC5kaWdpdHNbbl07DQogICAgdmFyIG0gPSAobiArIDEpICogYml0c1BlckRpZ2l0Ow0KICAgIHZhciByZXN1bHQ7DQogICAgZm9yIChyZXN1bHQgPSBtOyByZXN1bHQgPiBtIC0gYml0c1BlckRpZ2l0OyAtLXJlc3VsdCkgew0KICAgICAgICBpZiAoKGQgJiAweDgwMDApICE9IDApIGJyZWFrOw0KICAgICAgICBkIDw8PSAxOw0KICAgIH0NCiAgICByZXR1cm4gcmVzdWx0Ow0KfQ0KDQpmdW5jdGlvbiBiaU11bHRpcGx5KHgsIHkpDQp7DQogICAgdmFyIHJlc3VsdCA9IG5ldyBCaWdJbnQoKTsNCiAgICB2YXIgYzsNCiAgICB2YXIgbiA9IGJpSGlnaEluZGV4KHgpOw0KICAgIHZhciB0ID0gYmlIaWdoSW5kZXgoeSk7DQogICAgdmFyIHUsIHV2LCBrOw0KDQogICAgZm9yICh2YXIgaSA9IDA7IGkgPD0gdDsgKytpKSB7DQogICAgICAgIGMgPSAwOw0KICAgICAgICBrID0gaTsNCiAgICAgICAgZm9yIChqID0gMDsgaiA8PSBuOyArK2osICsraykgew0KICAgICAgICAgICAgdXYgPSByZXN1bHQuZGlnaXRzW2tdICsgeC5kaWdpdHNbal0gKiB5LmRpZ2l0c1tpXSArIGM7DQogICAgICAgICAgICByZXN1bHQuZGlnaXRzW2tdID0gdXYgJiBtYXhEaWdpdFZhbDsNCiAgICAgICAgICAgIGMgPSB1diA+Pj4gYmlSYWRpeEJpdHM7DQogICAgICAgICAgICAvL2MgPSBNYXRoLmZsb29yKHV2IC8gYmlSYWRpeCk7DQogICAgICAgIH0NCiAgICAgICAgcmVzdWx0LmRpZ2l0c1tpICsgbiArIDFdID0gYzsNCiAgICB9DQogICAgLy8gU29tZW9uZSBnaXZlIG1lIGEgbG9naWNhbCB4b3IsIHBsZWFzZS4NCiAgICByZXN1bHQuaXNOZWcgPSB4LmlzTmVnICE9IHkuaXNOZWc7DQogICAgcmV0dXJuIHJlc3VsdDsNCn0NCg0KZnVuY3Rpb24gYmlNdWx0aXBseURpZ2l0KHgsIHkpDQp7DQogICAgdmFyIG4sIGMsIHV2Ow0KDQogICAgcmVzdWx0ID0gbmV3IEJpZ0ludCgpOw0KICAgIG4gPSBiaUhpZ2hJbmRleCh4KTsNCiAgICBjID0gMDsNCiAgICBmb3IgKHZhciBqID0gMDsgaiA8PSBuOyArK2opIHsNCiAgICAgICAgdXYgPSByZXN1bHQuZGlnaXRzW2pdICsgeC5kaWdpdHNbal0gKiB5ICsgYzsNCiAgICAgICAgcmVzdWx0LmRpZ2l0c1tqXSA9IHV2ICYgbWF4RGlnaXRWYWw7DQogICAgICAgIGMgPSB1diA+Pj4gYmlSYWRpeEJpdHM7DQogICAgICAgIC8vYyA9IE1hdGguZmxvb3IodXYgLyBiaVJhZGl4KTsNCiAgICB9DQogICAgcmVzdWx0LmRpZ2l0c1sxICsgbl0gPSBjOw0KICAgIHJldHVybiByZXN1bHQ7DQp9DQoNCmZ1bmN0aW9uIGFycmF5Q29weShzcmMsIHNyY1N0YXJ0LCBkZXN0LCBkZXN0U3RhcnQsIG4pDQp7DQogICAgdmFyIG0gPSBNYXRoLm1pbihzcmNTdGFydCArIG4sIHNyYy5sZW5ndGgpOw0KICAgIGZvciAodmFyIGkgPSBzcmNTdGFydCwgaiA9IGRlc3RTdGFydDsgaSA8IG07ICsraSwgKytqKSB7DQogICAgICAgIGRlc3Rbal0gPSBzcmNbaV07DQogICAgfQ0KfQ0KDQp2YXIgaGlnaEJpdE1hc2tzID0gbmV3IEFycmF5KDB4MDAwMCwgMHg4MDAwLCAweEMwMDAsIDB4RTAwMCwgMHhGMDAwLCAweEY4MDAsDQogICAgMHhGQzAwLCAweEZFMDAsIDB4RkYwMCwgMHhGRjgwLCAweEZGQzAsIDB4RkZFMCwNCiAgICAweEZGRjAsIDB4RkZGOCwgMHhGRkZDLCAweEZGRkUsIDB4RkZGRik7DQoNCmZ1bmN0aW9uIGJpU2hpZnRMZWZ0KHgsIG4pDQp7DQogICAgdmFyIGRpZ2l0Q291bnQgPSBNYXRoLmZsb29yKG4gLyBiaXRzUGVyRGlnaXQpOw0KICAgIHZhciByZXN1bHQgPSBuZXcgQmlnSW50KCk7DQogICAgYXJyYXlDb3B5KHguZGlnaXRzLCAwLCByZXN1bHQuZGlnaXRzLCBkaWdpdENvdW50LA0KICAgICAgICByZXN1bHQuZGlnaXRzLmxlbmd0aCAtIGRpZ2l0Q291bnQpOw0KICAgIHZhciBiaXRzID0gbiAlIGJpdHNQZXJEaWdpdDsNCiAgICB2YXIgcmlnaHRCaXRzID0gYml0c1BlckRpZ2l0IC0gYml0czsNCiAgICBmb3IgKHZhciBpID0gcmVzdWx0LmRpZ2l0cy5sZW5ndGggLSAxLCBpMSA9IGkgLSAxOyBpID4gMDsgLS1pLCAtLWkxKSB7DQogICAgICAgIHJlc3VsdC5kaWdpdHNbaV0gPSAoKHJlc3VsdC5kaWdpdHNbaV0gPDwgYml0cykgJiBtYXhEaWdpdFZhbCkgfA0KICAgICAgICAgICAgKChyZXN1bHQuZGlnaXRzW2kxXSAmIGhpZ2hCaXRNYXNrc1tiaXRzXSkgPj4+DQogICAgICAgICAgICAocmlnaHRCaXRzKSk7DQogICAgfQ0KICAgIHJlc3VsdC5kaWdpdHNbMF0gPSAoKHJlc3VsdC5kaWdpdHNbaV0gPDwgYml0cykgJiBtYXhEaWdpdFZhbCk7DQogICAgcmVzdWx0LmlzTmVnID0geC5pc05lZzsNCiAgICByZXR1cm4gcmVzdWx0Ow0KfQ0KDQp2YXIgbG93Qml0TWFza3MgPSBuZXcgQXJyYXkoMHgwMDAwLCAweDAwMDEsIDB4MDAwMywgMHgwMDA3LCAweDAwMEYsIDB4MDAxRiwNCiAgICAweDAwM0YsIDB4MDA3RiwgMHgwMEZGLCAweDAxRkYsIDB4MDNGRiwgMHgwN0ZGLA0KICAgIDB4MEZGRiwgMHgxRkZGLCAweDNGRkYsIDB4N0ZGRiwgMHhGRkZGKTsNCg0KZnVuY3Rpb24gYmlTaGlmdFJpZ2h0KHgsIG4pDQp7DQogICAgdmFyIGRpZ2l0Q291bnQgPSBNYXRoLmZsb29yKG4gLyBiaXRzUGVyRGlnaXQpOw0KICAgIHZhciByZXN1bHQgPSBuZXcgQmlnSW50KCk7DQogICAgYXJyYXlDb3B5KHguZGlnaXRzLCBkaWdpdENvdW50LCByZXN1bHQuZGlnaXRzLCAwLA0KICAgICAgICB4LmRpZ2l0cy5sZW5ndGggLSBkaWdpdENvdW50KTsNCiAgICB2YXIgYml0cyA9IG4gJSBiaXRzUGVyRGlnaXQ7DQogICAgdmFyIGxlZnRCaXRzID0gYml0c1BlckRpZ2l0IC0gYml0czsNCiAgICBmb3IgKHZhciBpID0gMCwgaTEgPSBpICsgMTsgaSA8IHJlc3VsdC5kaWdpdHMubGVuZ3RoIC0gMTsgKytpLCArK2kxKSB7DQogICAgICAgIHJlc3VsdC5kaWdpdHNbaV0gPSAocmVzdWx0LmRpZ2l0c1tpXSA+Pj4gYml0cykgfA0KICAgICAgICAgICAgKChyZXN1bHQuZGlnaXRzW2kxXSAmIGxvd0JpdE1hc2tzW2JpdHNdKSA8PCBsZWZ0Qml0cyk7DQogICAgfQ0KICAgIHJlc3VsdC5kaWdpdHNbcmVzdWx0LmRpZ2l0cy5sZW5ndGggLSAxXSA+Pj49IGJpdHM7DQogICAgcmVzdWx0LmlzTmVnID0geC5pc05lZzsNCiAgICByZXR1cm4gcmVzdWx0Ow0KfQ0KDQpmdW5jdGlvbiBiaU11bHRpcGx5QnlSYWRpeFBvd2VyKHgsIG4pDQp7DQogICAgdmFyIHJlc3VsdCA9IG5ldyBCaWdJbnQoKTsNCiAgICBhcnJheUNvcHkoeC5kaWdpdHMsIDAsIHJlc3VsdC5kaWdpdHMsIG4sIHJlc3VsdC5kaWdpdHMubGVuZ3RoIC0gbik7DQogICAgcmV0dXJuIHJlc3VsdDsNCn0NCg0KZnVuY3Rpb24gYmlEaXZpZGVCeVJhZGl4UG93ZXIoeCwgbikNCnsNCiAgICB2YXIgcmVzdWx0ID0gbmV3IEJpZ0ludCgpOw0KICAgIGFycmF5Q29weSh4LmRpZ2l0cywgbiwgcmVzdWx0LmRpZ2l0cywgMCwgcmVzdWx0LmRpZ2l0cy5sZW5ndGggLSBuKTsNCiAgICByZXR1cm4gcmVzdWx0Ow0KfQ0KDQpmdW5jdGlvbiBiaU1vZHVsb0J5UmFkaXhQb3dlcih4LCBuKQ0Kew0KICAgIHZhciByZXN1bHQgPSBuZXcgQmlnSW50KCk7DQogICAgYXJyYXlDb3B5KHguZGlnaXRzLCAwLCByZXN1bHQuZGlnaXRzLCAwLCBuKTsNCiAgICByZXR1cm4gcmVzdWx0Ow0KfQ0KDQpmdW5jdGlvbiBiaUNvbXBhcmUoeCwgeSkNCnsNCiAgICBpZiAoeC5pc05lZyAhPSB5LmlzTmVnKSB7DQogICAgICAgIHJldHVybiAxIC0gMiAqIE51bWJlcih4LmlzTmVnKTsNCiAgICB9DQogICAgZm9yICh2YXIgaSA9IHguZGlnaXRzLmxlbmd0aCAtIDE7IGkgPj0gMDsgLS1pKSB7DQogICAgICAgIGlmICh4LmRpZ2l0c1tpXSAhPSB5LmRpZ2l0c1tpXSkgew0KICAgICAgICAgICAgaWYgKHguaXNOZWcpIHsNCiAgICAgICAgICAgICAgICByZXR1cm4gMSAtIDIgKiBOdW1iZXIoeC5kaWdpdHNbaV0gPiB5LmRpZ2l0c1tpXSk7DQogICAgICAgICAgICB9IGVsc2Ugew0KICAgICAgICAgICAgICAgIHJldHVybiAxIC0gMiAqIE51bWJlcih4LmRpZ2l0c1tpXSA8IHkuZGlnaXRzW2ldKTsNCiAgICAgICAgICAgIH0NCiAgICAgICAgfQ0KICAgIH0NCiAgICByZXR1cm4gMDsNCn0NCg0KZnVuY3Rpb24gYmlEaXZpZGVNb2R1bG8oeCwgeSkNCnsNCiAgICB2YXIgbmIgPSBiaU51bUJpdHMoeCk7DQogICAgdmFyIHRiID0gYmlOdW1CaXRzKHkpOw0KICAgIHZhciBvcmlnWUlzTmVnID0geS5pc05lZzsNCiAgICB2YXIgcSwgcjsNCiAgICBpZiAobmIgPCB0Yikgew0KICAgICAgICAvLyB8eHwgPCB8eXwNCiAgICAgICAgaWYgKHguaXNOZWcpIHsNCiAgICAgICAgICAgIHEgPSBiaUNvcHkoYmlnT25lKTsNCiAgICAgICAgICAgIHEuaXNOZWcgPSAheS5pc05lZzsNCiAgICAgICAgICAgIHguaXNOZWcgPSBmYWxzZTsNCiAgICAgICAgICAgIHkuaXNOZWcgPSBmYWxzZTsNCiAgICAgICAgICAgIHIgPSBiaVN1YnRyYWN0KHksIHgpOw0KICAgICAgICAgICAgLy8gUmVzdG9yZSBzaWducywgJ2NhdXNlIHRoZXkncmUgcmVmZXJlbmNlcy4NCiAgICAgICAgICAgIHguaXNOZWcgPSB0cnVlOw0KICAgICAgICAgICAgeS5pc05lZyA9IG9yaWdZSXNOZWc7DQogICAgICAgIH0gZWxzZSB7DQogICAgICAgICAgICBxID0gbmV3IEJpZ0ludCgpOw0KICAgICAgICAgICAgciA9IGJpQ29weSh4KTsNCiAgICAgICAgfQ0KICAgICAgICByZXR1cm4gbmV3IEFycmF5KHEsIHIpOw0KICAgIH0NCg0KICAgIHEgPSBuZXcgQmlnSW50KCk7DQogICAgciA9IHg7DQoNCiAgICAvLyBOb3JtYWxpemUgWS4NCiAgICB2YXIgdCA9IE1hdGguY2VpbCh0YiAvIGJpdHNQZXJEaWdpdCkgLSAxOw0KICAgIHZhciBsYW1iZGEgPSAwOw0KICAgIHdoaWxlICh5LmRpZ2l0c1t0XSA8IGJpSGFsZlJhZGl4KSB7DQogICAgICAgIHkgPSBiaVNoaWZ0TGVmdCh5LCAxKTsNCiAgICAgICAgKytsYW1iZGE7DQogICAgICAgICsrdGI7DQogICAgICAgIHQgPSBNYXRoLmNlaWwodGIgLyBiaXRzUGVyRGlnaXQpIC0gMTsNCiAgICB9DQogICAgLy8gU2hpZnQgciBvdmVyIHRvIGtlZXAgdGhlIHF1b3RpZW50IGNvbnN0YW50LiBXZSdsbCBzaGlmdCB0aGUNCiAgICAvLyByZW1haW5kZXIgYmFjayBhdCB0aGUgZW5kLg0KICAgIHIgPSBiaVNoaWZ0TGVmdChyLCBsYW1iZGEpOw0KICAgIG5iICs9IGxhbWJkYTsgLy8gVXBkYXRlIHRoZSBiaXQgY291bnQgZm9yIHguDQogICAgdmFyIG4gPSBNYXRoLmNlaWwobmIgLyBiaXRzUGVyRGlnaXQpIC0gMTsNCg0KICAgIHZhciBiID0gYmlNdWx0aXBseUJ5UmFkaXhQb3dlcih5LCBuIC0gdCk7DQogICAgd2hpbGUgKGJpQ29tcGFyZShyLCBiKSAhPSAtMSkgew0KICAgICAgICArK3EuZGlnaXRzW24gLSB0XTsNCiAgICAgICAgciA9IGJpU3VidHJhY3QociwgYik7DQogICAgfQ0KICAgIGZvciAodmFyIGkgPSBuOyBpID4gdDsgLS1pKSB7DQogICAgICAgIHZhciByaSA9IChpID49IHIuZGlnaXRzLmxlbmd0aCkgPyAwIDogci5kaWdpdHNbaV07DQogICAgICAgIHZhciByaTEgPSAoaSAtIDEgPj0gci5kaWdpdHMubGVuZ3RoKSA/IDAgOiByLmRpZ2l0c1tpIC0gMV07DQogICAgICAgIHZhciByaTIgPSAoaSAtIDIgPj0gci5kaWdpdHMubGVuZ3RoKSA/IDAgOiByLmRpZ2l0c1tpIC0gMl07DQogICAgICAgIHZhciB5dCA9ICh0ID49IHkuZGlnaXRzLmxlbmd0aCkgPyAwIDogeS5kaWdpdHNbdF07DQogICAgICAgIHZhciB5dDEgPSAodCAtIDEgPj0geS5kaWdpdHMubGVuZ3RoKSA/IDAgOiB5LmRpZ2l0c1t0IC0gMV07DQogICAgICAgIGlmIChyaSA9PSB5dCkgew0KICAgICAgICAgICAgcS5kaWdpdHNbaSAtIHQgLSAxXSA9IG1heERpZ2l0VmFsOw0KICAgICAgICB9IGVsc2Ugew0KICAgICAgICAgICAgcS5kaWdpdHNbaSAtIHQgLSAxXSA9IE1hdGguZmxvb3IoKHJpICogYmlSYWRpeCArIHJpMSkgLyB5dCk7DQogICAgICAgIH0NCg0KICAgICAgICB2YXIgYzEgPSBxLmRpZ2l0c1tpIC0gdCAtIDFdICogKCh5dCAqIGJpUmFkaXgpICsgeXQxKTsNCiAgICAgICAgdmFyIGMyID0gKHJpICogYmlSYWRpeFNxdWFyZWQpICsgKChyaTEgKiBiaVJhZGl4KSArIHJpMik7DQogICAgICAgIHdoaWxlIChjMSA+IGMyKSB7DQogICAgICAgICAgICAtLXEuZGlnaXRzW2kgLSB0IC0gMV07DQogICAgICAgICAgICBjMSA9IHEuZGlnaXRzW2kgLSB0IC0gMV0gKiAoKHl0ICogYmlSYWRpeCkgfCB5dDEpOw0KICAgICAgICAgICAgYzIgPSAocmkgKiBiaVJhZGl4ICogYmlSYWRpeCkgKyAoKHJpMSAqIGJpUmFkaXgpICsgcmkyKTsNCiAgICAgICAgfQ0KDQogICAgICAgIGIgPSBiaU11bHRpcGx5QnlSYWRpeFBvd2VyKHksIGkgLSB0IC0gMSk7DQogICAgICAgIHIgPSBiaVN1YnRyYWN0KHIsIGJpTXVsdGlwbHlEaWdpdChiLCBxLmRpZ2l0c1tpIC0gdCAtIDFdKSk7DQogICAgICAgIGlmIChyLmlzTmVnKSB7DQogICAgICAgICAgICByID0gYmlBZGQociwgYik7DQogICAgICAgICAgICAtLXEuZGlnaXRzW2kgLSB0IC0gMV07DQogICAgICAgIH0NCiAgICB9DQogICAgciA9IGJpU2hpZnRSaWdodChyLCBsYW1iZGEpOw0KICAgIC8vIEZpZGRsZSB3aXRoIHRoZSBzaWducyBhbmQgc3R1ZmYgdG8gbWFrZSBzdXJlIHRoYXQgMCA8PSByIDwgeS4NCiAgICBxLmlzTmVnID0geC5pc05lZyAhPSBvcmlnWUlzTmVnOw0KICAgIGlmICh4LmlzTmVnKSB7DQogICAgICAgIGlmIChvcmlnWUlzTmVnKSB7DQogICAgICAgICAgICBxID0gYmlBZGQocSwgYmlnT25lKTsNCiAgICAgICAgfSBlbHNlIHsNCiAgICAgICAgICAgIHEgPSBiaVN1YnRyYWN0KHEsIGJpZ09uZSk7DQogICAgICAgIH0NCiAgICAgICAgeSA9IGJpU2hpZnRSaWdodCh5LCBsYW1iZGEpOw0KICAgICAgICByID0gYmlTdWJ0cmFjdCh5LCByKTsNCiAgICB9DQogICAgLy8gQ2hlY2sgZm9yIHRoZSB1bmJlbGlldmFibHkgc3R1cGlkIGRlZ2VuZXJhdGUgY2FzZSBvZiByID09IC0wLg0KICAgIGlmIChyLmRpZ2l0c1swXSA9PSAwICYmIGJpSGlnaEluZGV4KHIpID09IDApIHIuaXNOZWcgPSBmYWxzZTsNCg0KICAgIHJldHVybiBuZXcgQXJyYXkocSwgcik7DQp9DQoNCmZ1bmN0aW9uIGJpRGl2aWRlKHgsIHkpDQp7DQogICAgcmV0dXJuIGJpRGl2aWRlTW9kdWxvKHgsIHkpWzBdOw0KfQ0KDQpmdW5jdGlvbiBiaU1vZHVsbyh4LCB5KQ0Kew0KICAgIHJldHVybiBiaURpdmlkZU1vZHVsbyh4LCB5KVsxXTsNCn0NCg0KZnVuY3Rpb24gYmlNdWx0aXBseU1vZCh4LCB5LCBtKQ0Kew0KICAgIHJldHVybiBiaU1vZHVsbyhiaU11bHRpcGx5KHgsIHkpLCBtKTsNCn0NCg0KZnVuY3Rpb24gYmlQb3coeCwgeSkNCnsNCiAgICB2YXIgcmVzdWx0ID0gYmlnT25lOw0KICAgIHZhciBhID0geDsNCiAgICB3aGlsZSAodHJ1ZSkgew0KICAgICAgICBpZiAoKHkgJiAxKSAhPSAwKSByZXN1bHQgPSBiaU11bHRpcGx5KHJlc3VsdCwgYSk7DQogICAgICAgIHkgPj49IDE7DQogICAgICAgIGlmICh5ID09IDApIGJyZWFrOw0KICAgICAgICBhID0gYmlNdWx0aXBseShhLCBhKTsNCiAgICB9DQogICAgcmV0dXJuIHJlc3VsdDsNCn0NCg0KZnVuY3Rpb24gYmlQb3dNb2QoeCwgeSwgbSkNCnsNCiAgICB2YXIgcmVzdWx0ID0gYmlnT25lOw0KICAgIHZhciBhID0geDsNCiAgICB2YXIgayA9IHk7DQogICAgd2hpbGUgKHRydWUpIHsNCiAgICAgICAgaWYgKChrLmRpZ2l0c1swXSAmIDEpICE9IDApIHJlc3VsdCA9IGJpTXVsdGlwbHlNb2QocmVzdWx0LCBhLCBtKTsNCiAgICAgICAgayA9IGJpU2hpZnRSaWdodChrLCAxKTsNCiAgICAgICAgaWYgKGsuZGlnaXRzWzBdID09IDAgJiYgYmlIaWdoSW5kZXgoaykgPT0gMCkgYnJlYWs7DQogICAgICAgIGEgPSBiaU11bHRpcGx5TW9kKGEsIGEsIG0pOw0KICAgIH0NCiAgICByZXR1cm4gcmVzdWx0Ow0KfQ0KDQovLyBCYXJyZXR0TXUsIGEgY2xhc3MgZm9yIHBlcmZvcm1pbmcgQmFycmV0dCBtb2R1bGFyIHJlZHVjdGlvbiBjb21wdXRhdGlvbnMgaW4NCi8vIEphdmFTY3JpcHQuDQovLw0KLy8gUmVxdWlyZXMgQmlnSW50LmpzLg0KLy8NCi8vIENvcHlyaWdodCAyMDA0LTIwMDUgRGF2aWQgU2hhcGlyby4NCi8vDQovLyBZb3UgbWF5IHVzZSwgcmUtdXNlLCBhYnVzZSwgY29weSwgYW5kIG1vZGlmeSB0aGlzIGNvZGUgdG8geW91ciBsaWtpbmcsIGJ1dA0KLy8gcGxlYXNlIGtlZXAgdGhpcyBoZWFkZXIuDQovLw0KLy8gVGhhbmtzIQ0KLy8gDQovLyBEYXZlIFNoYXBpcm8NCi8vIGRhdmVAb2hkYXZlLmNvbSANCg0KZnVuY3Rpb24gQmFycmV0dE11KG0pDQp7DQogICAgdGhpcy5tb2R1bHVzID0gYmlDb3B5KG0pOw0KICAgIHRoaXMuayA9IGJpSGlnaEluZGV4KHRoaXMubW9kdWx1cykgKyAxOw0KICAgIHZhciBiMmsgPSBuZXcgQmlnSW50KCk7DQogICAgYjJrLmRpZ2l0c1syICogdGhpcy5rXSA9IDE7IC8vIGIyayA9IGJeKDJrKQ0KICAgIHRoaXMubXUgPSBiaURpdmlkZShiMmssIHRoaXMubW9kdWx1cyk7DQogICAgdGhpcy5ia3BsdXMxID0gbmV3IEJpZ0ludCgpOw0KICAgIHRoaXMuYmtwbHVzMS5kaWdpdHNbdGhpcy5rICsgMV0gPSAxOyAvLyBia3BsdXMxID0gYl4oaysxKQ0KICAgIHRoaXMubW9kdWxvID0gQmFycmV0dE11X21vZHVsbzsNCiAgICB0aGlzLm11bHRpcGx5TW9kID0gQmFycmV0dE11X211bHRpcGx5TW9kOw0KICAgIHRoaXMucG93TW9kID0gQmFycmV0dE11X3Bvd01vZDsNCn0NCg0KZnVuY3Rpb24gQmFycmV0dE11X21vZHVsbyh4KQ0Kew0KICAgIHZhciBxMSA9IGJpRGl2aWRlQnlSYWRpeFBvd2VyKHgsIHRoaXMuayAtIDEpOw0KICAgIHZhciBxMiA9IGJpTXVsdGlwbHkocTEsIHRoaXMubXUpOw0KICAgIHZhciBxMyA9IGJpRGl2aWRlQnlSYWRpeFBvd2VyKHEyLCB0aGlzLmsgKyAxKTsNCiAgICB2YXIgcjEgPSBiaU1vZHVsb0J5UmFkaXhQb3dlcih4LCB0aGlzLmsgKyAxKTsNCiAgICB2YXIgcjJ0ZXJtID0gYmlNdWx0aXBseShxMywgdGhpcy5tb2R1bHVzKTsNCiAgICB2YXIgcjIgPSBiaU1vZHVsb0J5UmFkaXhQb3dlcihyMnRlcm0sIHRoaXMuayArIDEpOw0KICAgIHZhciByID0gYmlTdWJ0cmFjdChyMSwgcjIpOw0KICAgIGlmIChyLmlzTmVnKSB7DQogICAgICAgIHIgPSBiaUFkZChyLCB0aGlzLmJrcGx1czEpOw0KICAgIH0NCiAgICB2YXIgcmd0ZW0gPSBiaUNvbXBhcmUociwgdGhpcy5tb2R1bHVzKSA+PSAwOw0KICAgIHdoaWxlIChyZ3RlbSkgew0KICAgICAgICByID0gYmlTdWJ0cmFjdChyLCB0aGlzLm1vZHVsdXMpOw0KICAgICAgICByZ3RlbSA9IGJpQ29tcGFyZShyLCB0aGlzLm1vZHVsdXMpID49IDA7DQogICAgfQ0KICAgIHJldHVybiByOw0KfQ0KDQpmdW5jdGlvbiBCYXJyZXR0TXVfbXVsdGlwbHlNb2QoeCwgeSkNCnsNCgkvKg0KCSB4ID0gdGhpcy5tb2R1bG8oeCk7DQoJIHkgPSB0aGlzLm1vZHVsbyh5KTsNCgkgKi8NCiAgICB2YXIgeHkgPSBiaU11bHRpcGx5KHgsIHkpOw0KICAgIHJldHVybiB0aGlzLm1vZHVsbyh4eSk7DQp9DQoNCmZ1bmN0aW9uIEJhcnJldHRNdV9wb3dNb2QoeCwgeSkNCnsNCiAgICB2YXIgcmVzdWx0ID0gbmV3IEJpZ0ludCgpOw0KICAgIHJlc3VsdC5kaWdpdHNbMF0gPSAxOw0KICAgIHZhciBhID0geDsNCiAgICB2YXIgayA9IHk7DQogICAgd2hpbGUgKHRydWUpIHsNCiAgICAgICAgaWYgKChrLmRpZ2l0c1swXSAmIDEpICE9IDApIHJlc3VsdCA9IHRoaXMubXVsdGlwbHlNb2QocmVzdWx0LCBhKTsNCiAgICAgICAgayA9IGJpU2hpZnRSaWdodChrLCAxKTsNCiAgICAgICAgaWYgKGsuZGlnaXRzWzBdID09IDAgJiYgYmlIaWdoSW5kZXgoaykgPT0gMCkgYnJlYWs7DQogICAgICAgIGEgPSB0aGlzLm11bHRpcGx5TW9kKGEsIGEpOw0KICAgIH0NCiAgICByZXR1cm4gcmVzdWx0Ow0KfQ0KDQoNCi8vIFJTQSwgYSBzdWl0ZSBvZiByb3V0aW5lcyBmb3IgcGVyZm9ybWluZyBSU0EgcHVibGljLWtleSBjb21wdXRhdGlvbnMgaW4NCi8vIEphdmFTY3JpcHQuDQovLw0KLy8gUmVxdWlyZXMgQmlnSW50LmpzIGFuZCBCYXJyZXR0LmpzLg0KLy8NCi8vIENvcHlyaWdodCAxOTk4LTIwMDUgRGF2aWQgU2hhcGlyby4NCi8vDQovLyBZb3UgbWF5IHVzZSwgcmUtdXNlLCBhYnVzZSwgY29weSwgYW5kIG1vZGlmeSB0aGlzIGNvZGUgdG8geW91ciBsaWtpbmcsIGJ1dA0KLy8gcGxlYXNlIGtlZXAgdGhpcyBoZWFkZXIuDQovLw0KLy8gVGhhbmtzIQ0KLy8gDQovLyBEYXZlIFNoYXBpcm8NCi8vIGRhdmVAb2hkYXZlLmNvbSANCg0KZnVuY3Rpb24gUlNBS2V5UGFpcihlbmNyeXB0aW9uRXhwb25lbnQsIGRlY3J5cHRpb25FeHBvbmVudCwgbW9kdWx1cykNCnsNCiAgICB0aGlzLmUgPSBiaUZyb21IZXgoZW5jcnlwdGlvbkV4cG9uZW50KTsNCiAgICB0aGlzLmQgPSBiaUZyb21IZXgoZGVjcnlwdGlvbkV4cG9uZW50KTsNCiAgICB0aGlzLm0gPSBiaUZyb21IZXgobW9kdWx1cyk7DQogICAgLy8gV2UgY2FuIGRvIHR3byBieXRlcyBwZXIgZGlnaXQsIHNvDQogICAgLy8gY2h1bmtTaXplID0gMiAqIChudW1iZXIgb2YgZGlnaXRzIGluIG1vZHVsdXMgLSAxKS4NCiAgICAvLyBTaW5jZSBiaUhpZ2hJbmRleCByZXR1cm5zIHRoZSBoaWdoIGluZGV4LCBub3QgdGhlIG51bWJlciBvZiBkaWdpdHMsIDEgaGFzDQogICAgLy8gYWxyZWFkeSBiZWVuIHN1YnRyYWN0ZWQuDQogICAgdGhpcy5jaHVua1NpemUgPSAyICogYmlIaWdoSW5kZXgodGhpcy5tKTsNCiAgICB0aGlzLnJhZGl4ID0gMTY7DQogICAgdGhpcy5iYXJyZXR0ID0gbmV3IEJhcnJldHRNdSh0aGlzLm0pOw0KfQ0KDQpmdW5jdGlvbiB0d29EaWdpdChuKQ0Kew0KICAgIHJldHVybiAobiA8IDEwID8gIjAiIDogIiIpICsgU3RyaW5nKG4pOw0KfQ0KDQpmdW5jdGlvbiBib2R5UlNBKCkNCnsNCiAgICBzZXRNYXhEaWdpdHMoMTMwKTsNCiAgICByZXR1cm4gbmV3IFJTQUtleVBhaXIoIjEwMDAxIiwiIiwiYTVhZWI4YzYzNmVmMWZkYTVhN2ExN2EyODE5ZTUxZTFlYTZlMGNjZWIyNGI5NTU3NGFlMDI2NTM2MjQzNTI0ZjMyMjgwN2RmMjUzMWE0MjEzOTM4OTY3NDU0NWY0YzU5NmRiMTYyZjZlNmJiYjI2NDk4YmFhYjA3NGMwMzY3NzciKTsNCiAgICAvL3JldHVybiBuZXcgUlNBS2V5UGFpcigiMTAwMDEiLCIiLCJmZHNzZmRzZmRzZmRzZmRzIik7DQp9DQoNCmZ1bmN0aW9uIGVuY3J5cHRlZFN0cmluZyhzKQ0KLy8gQWx0ZXJlZCBieSBSb2IgU2F1bmRlcnMgKHJvYkByb2JzYXVuZGVycy5uZXQpLiBOZXcgcm91dGluZSBwYWRzIHRoZQ0KLy8gc3RyaW5nIGFmdGVyIGl0IGhhcyBiZWVuIGNvbnZlcnRlZCB0byBhbiBhcnJheS4gVGhpcyBmaXhlcyBhbg0KLy8gaW5jb21wYXRpYmlsaXR5IHdpdGggRmxhc2ggTVgncyBBY3Rpb25TY3JpcHQuDQp7DQogICAgdmFyIGtleSA9ICBuZXcgUlNBS2V5UGFpcigiMTAwMDEiLCIiLCJhNWFlYjhjNjM2ZWYxZmRhNWE3YTE3YTI4MTllNTFlMWVhNmUwY2NlYjI0Yjk1NTc0YWUwMjY1MzYyNDM1MjRmMzIyODA3ZGYyNTMxYTQyMTM5Mzg5Njc0NTQ1ZjRjNTk2ZGIxNjJmNmU2YmJiMjY0OThiYWFiMDc0YzAzNjc3NyIpOw0KDQogICAgdmFyIGEgPSBuZXcgQXJyYXkoKTsNCiAgICB2YXIgc2wgPSBzLmxlbmd0aDsNCiAgICB2YXIgaSA9IDA7DQogICAgd2hpbGUgKGkgPCBzbCkgew0KICAgICAgICBhW2ldID0gcy5jaGFyQ29kZUF0KGkpOw0KICAgICAgICBpKys7DQogICAgfQ0KDQogICAgd2hpbGUgKGEubGVuZ3RoICUga2V5LmNodW5rU2l6ZSAhPSAwKSB7DQogICAgICAgIGFbaSsrXSA9IDA7DQogICAgfQ0KDQogICAgdmFyIGFsID0gYS5sZW5ndGg7DQogICAgdmFyIHJlc3VsdCA9ICIiOw0KICAgIHZhciBqLCBrLCBibG9jazsNCiAgICBmb3IgKGkgPSAwOyBpIDwgYWw7IGkgKz0ga2V5LmNodW5rU2l6ZSkgew0KICAgICAgICBibG9jayA9IG5ldyBCaWdJbnQoKTsNCiAgICAgICAgaiA9IDA7DQogICAgICAgIGZvciAoayA9IGk7IGsgPCBpICsga2V5LmNodW5rU2l6ZTsgKytqKSB7DQogICAgICAgICAgICBibG9jay5kaWdpdHNbal0gPSBhW2srK107DQogICAgICAgICAgICBibG9jay5kaWdpdHNbal0gKz0gYVtrKytdIDw8IDg7DQogICAgICAgIH0NCiAgICAgICAgdmFyIGNyeXB0ID0ga2V5LmJhcnJldHQucG93TW9kKGJsb2NrLCBrZXkuZSk7DQogICAgICAgIHZhciB0ZXh0ID0ga2V5LnJhZGl4ID09IDE2ID8gYmlUb0hleChjcnlwdCkgOiBiaVRvU3RyaW5nKGNyeXB0LCBrZXkucmFkaXgpOw0KICAgICAgICByZXN1bHQgKz0gdGV4dCArICIgIjsNCiAgICB9DQogICAgcmV0dXJuIHJlc3VsdC5zdWJzdHJpbmcoMCwgcmVzdWx0Lmxlbmd0aCAtIDEpOyAvLyBSZW1vdmUgbGFzdCBzcGFjZS4NCn0NCg0KZnVuY3Rpb24gZGVjcnlwdGVkU3RyaW5nKHMpDQp7DQogICAgZnVuY3Rpb24gYm9keVJTQSgpDQogICAgew0KICAgICAgICBzZXRNYXhEaWdpdHMoMTMwKTsNCiAgICAgICAgcmV0dXJuIG5ldyBSU0FLZXlQYWlyKCIxMDAwMSIsIiIsImE1YWViOGM2MzZlZjFmZGE1YTdhMTdhMjgxOWU1MWUxZWE2ZTBjY2ViMjRiOTU1NzRhZTAyNjUzNjI0MzUyNGYzMjI4MDdkZjI1MzFhNDIxMzkzODk2NzQ1NDVmNGM1OTZkYjE2MmY2ZTZiYmIyNjQ5OGJhYWIwNzRjMDM2Nzc3Iik7DQogICAgfQ0KICAgIHZhciBrZXkgPSAgYm9keVJTQSgpOw0KICAgIHZhciBibG9ja3MgPSBzLnNwbGl0KCIgIik7DQogICAgdmFyIHJlc3VsdCA9ICIiOw0KICAgIHZhciBpLCBqLCBibG9jazsNCiAgICBmb3IgKGkgPSAwOyBpIDwgYmxvY2tzLmxlbmd0aDsgKytpKSB7DQogICAgICAgIHZhciBiaTsNCiAgICAgICAgaWYgKGtleS5yYWRpeCA9PSAxNikgew0KICAgICAgICAgICAgYmkgPSBiaUZyb21IZXgoYmxvY2tzW2ldKTsNCiAgICAgICAgfQ0KICAgICAgICBlbHNlIHsNCiAgICAgICAgICAgIGJpID0gYmlGcm9tU3RyaW5nKGJsb2Nrc1tpXSwga2V5LnJhZGl4KTsNCiAgICAgICAgfQ0KICAgICAgICBibG9jayA9IGtleS5iYXJyZXR0LnBvd01vZChiaSwga2V5LmQpOw0KICAgICAgICBmb3IgKGogPSAwOyBqIDw9IGJpSGlnaEluZGV4KGJsb2NrKTsgKytqKSB7DQogICAgICAgICAgICByZXN1bHQgKz0gU3RyaW5nLmZyb21DaGFyQ29kZShibG9jay5kaWdpdHNbal0gJiAyNTUsDQogICAgICAgICAgICAgICAgYmxvY2suZGlnaXRzW2pdID4+IDgpOw0KICAgICAgICB9DQogICAgfQ0KICAgIC8vIFJlbW92ZSB0cmFpbGluZyBudWxsLCBpZiBhbnkuDQogICAgaWYgKHJlc3VsdC5jaGFyQ29kZUF0KHJlc3VsdC5sZW5ndGggLSAxKSA9PSAwKSB7DQogICAgICAgIHJlc3VsdCA9IHJlc3VsdC5zdWJzdHJpbmcoMCwgcmVzdWx0Lmxlbmd0aCAtIDEpOw0KICAgIH0NCiAgICByZXR1cm4gcmVzdWx0Ow0KfQ==";

    @Override
    public HttpResult<Map<String, Object>> init(OperatorParam param) {
        HttpResult<Map<String, Object>> result = new HttpResult<>();
        try {
            return result.success();
        } catch (Exception e) {
            logger.error("登录-->初始化失败,param={}", param, e);
            return result.failure(ErrorCode.TASK_INIT_ERROR);
        }
    }

    @Override
    public HttpResult<String> refeshPicCode(OperatorParam param) {
        switch (param.getFormType()) {
            case FormType.LOGIN:
                return refeshPicCodeForLogin(param);
            default:
                return new HttpResult<String>().failure(ErrorCode.NOT_SUPORT_METHOD);
        }
    }

    @Override
    public HttpResult<Map<String, Object>> validatePicCode(OperatorParam param) {
        switch (param.getFormType()) {
            case FormType.LOGIN:
                return validatePicCodeForLogin(param);
            default:
                return new HttpResult<Map<String, Object>>().failure(ErrorCode.NOT_SUPORT_METHOD);
        }
    }

    @Override
    public HttpResult<Map<String, Object>> refeshSmsCode(OperatorParam param) {
        switch (param.getFormType()) {
            case FormType.VALIDATE_BILL_DETAIL:
                return refeshSmsCodeForBillDetail(param);
            default:
                return new HttpResult<Map<String, Object>>().failure(ErrorCode.NOT_SUPORT_METHOD);
        }
    }


    @Override
    public HttpResult<Object> defineProcess(OperatorParam param) {
        switch (param.getFormType()) {
            case "EXPORT_PDF":
                return processForPdf(param);
            default:
                return new HttpResult<Object>().failure(ErrorCode.NOT_SUPORT_METHOD);
        }
    }

    @Override
    public HttpResult<Map<String, Object>> submit(OperatorParam param) {
        switch (param.getFormType()) {
            case FormType.LOGIN:
                return submitForLogin(param);
            case FormType.VALIDATE_BILL_DETAIL:
                return submitForBillDetail(param);
            default:
                return new HttpResult<Map<String, Object>>().failure(ErrorCode.NOT_SUPORT_METHOD);
        }
    }


    private HttpResult<String> refeshPicCodeForLogin(OperatorParam param) {
        HttpResult<String> result = new HttpResult<>();
        Response response = null;
        try {
            String templateUrl = "http://ah.189.cn/sso/VImage.servlet?random=" + System.currentTimeMillis();
            String referer = "http://ah.189.cn/sso/login?returnUrl=%2Fservice%2Faccount%2Finit.action";
            response = TaskHttpClient.create(param, RequestType.GET, "an_hui_10000_web_001").setFullUrl(templateUrl).setReferer(referer).invoke();
            logger.info("登录-->图片验证码-->刷新成功,param={}", param);
            return result.success(response.getPageContentForBase64());
        } catch (Exception e) {
            logger.error("登录-->图片验证码-->刷新失败,param={},response={}", param, response, e);
            return result.failure(ErrorCode.REFESH_PIC_CODE_ERROR);
        }
    }

    private HttpResult<Map<String, Object>> validatePicCodeForLogin(OperatorParam param) {
        CheckUtils.checkNotBlank(param.getPicCode(), ErrorCode.EMPTY_PIC_CODE);
        HttpResult<Map<String, Object>> result = new HttpResult<>();
        Response response = null;
        try {
            String templateUrl = "http://ah.189.cn/sso/ValidateRandom?validCode=" + param.getPicCode();
            String referer = "http://ah.189.cn/sso/login?returnUrl=%2Fservice%2Faccount%2Finit.action";
            response = TaskHttpClient.create(param, RequestType.POST, "an_hui_10000_web_002").setFullUrl(templateUrl).setReferer(referer).invoke();
            String pageContent = response.getPageContent();
            if (StringUtils.contains(pageContent, "true")) {
                logger.info("登录-->图片验证码-->校验成功,param={}", param);
                return result.success();
            } else {
                logger.error("登录-->图片验证码-->校验失败,param={},pageContent={}", param, response.getPageContent());
                return result.failure(ErrorCode.VALIDATE_PIC_CODE_UNEXPECTED_RESULT);
            }
        } catch (Exception e) {
            logger.error("登录-->图片验证码-->校验失败,param={},response={}", param, response, e);
            return result.failure(ErrorCode.VALIDATE_PIC_CODE_ERROR);
        }
    }

    private HttpResult<Map<String, Object>> submitForLogin(OperatorParam param) {
        CheckUtils.checkNotBlank(param.getPassword(), ErrorCode.EMPTY_PASSWORD);
        HttpResult<Map<String, Object>> result = validatePicCodeForLogin(param);
        if (!result.getStatus()) {
            return result;
        }
        Response response = null;
        try {
            Invocable invocable = ScriptEngineUtil.createInvocableFromBase64(javaScript);
            String encryptPassword = invocable.invokeFunction("encryptedString", param.getPassword()).toString();

            String templateUrl = "http://ah.189.cn/sso/LoginServlet";
            String referer = "http://ah.189.cn/sso/login?returnUrl=%2Fservice%2Faccount%2Finit.action";
            String templateData = "ssoAuth=0&returnUrl=%2Fservice%2Faccount%2Finit.action&sysId=1003&loginType=4&accountType=9&latnId=551&loginName={}"
                    + "&passType=0&passWord={}&validCode={}&csrftoken=" ;
            String data = TemplateUtils.format(templateData, param.getMobile(), encryptPassword,param.getPicCode());
            response = TaskHttpClient.create(param, RequestType.POST, "an_hui_10000_web_003").setFullUrl(templateUrl).setReferer(referer)
                    .setRequestBody(data).invoke();
            String pageContent = response.getPageContent();
            if(StringUtils.isBlank(pageContent)){
                logger.error("登陆失败,param={},response={}", param, response);
                return result.failure(ErrorCode.LOGIN_UNEXPECTED_RESULT);
            }
            String ssoValue = PatternUtils.group(pageContent, "value=\"([^\"]+)", 1);
            templateUrl = "http://uam.ah.ct10000.com/ffcs-uam/login?SSORequestXML=" + URLEncoder.encode(ssoValue, "UTF-8");
            referer = "http://ah.189.cn/sso/LoginServlet";
            response = TaskHttpClient.create(param, RequestType.POST, "an_hui_10000_web_004").setFullUrl(templateUrl).setReferer(referer)
                    .invoke();
            pageContent = response.getPageContent();
            if(StringUtils.isBlank(pageContent)){
                logger.error("登陆失败,param={},response={}", param, response);
                return result.failure(ErrorCode.LOGIN_UNEXPECTED_RESULT);
            }
            String resultMessage = PatternUtils.group(pageContent, "var returnmsg = \"([^\"]+)\"", 1);
            if (StringUtils.isNotBlank(resultMessage)) {
                logger.error("登陆失败,param={},response={}", param, resultMessage);
                return result.failure(ErrorCode.LOGIN_UNEXPECTED_RESULT);
            }
            templateUrl = "http://ah.189.cn/service/account/usedBalance.action?serviceNum=" + param.getMobile();
            referer = "http://ah.189.cn/service/account/init.action";
            response = TaskHttpClient.create(param, RequestType.POST, "an_hui_10000_web_005").setFullUrl(templateUrl).setReferer(referer)
                    .invoke();
            pageContent = response.getPageContent();
            if (StringUtils.isNotBlank(pageContent) && pageContent.contains("成功")) {
                String uuid = invocable.invokeFunction("encryptedString", "serviceNbr=" + param.getMobile()).toString();
                if (StringUtils.isBlank(uuid)) {
                    logger.error("获取uuid失败");
                    return result.failure(ErrorCode.LOGIN_UNEXPECTED_RESULT);
                }
                TaskUtils.addTaskShare(param.getTaskId(), "uuid", uuid);
                logger.info("登陆成功,param={}", param);
                return result.success();
            } else {
                logger.error("登陆失败,param={},pageContent={}", param, pageContent);
                return result.failure(ErrorCode.LOGIN_UNEXPECTED_RESULT);
            }
        } catch (Exception e) {
            logger.error("登陆失败,param={},response={}", param, response, e);
            return result.failure(ErrorCode.LOGIN_ERROR);
        }
    }


    private HttpResult<Map<String,Object>> refeshSmsCodeForBillDetail(OperatorParam param) {
        HttpResult<Map<String, Object>> result = new HttpResult<>();
        Response response = null;
        String mobile = String.valueOf(param.getMobile());
        try{
            Invocable invocable = ScriptEngineUtil.createInvocableFromBase64(javaScript);
            String data = invocable.invokeFunction("encryptedString", "mobileNum=" + param.getMobile() + "&key=" + mobile.substring(1, 2)
                    + mobile.substring(3, 4) + mobile.substring(6, 7) + mobile.substring(8, 10)).toString();
            String referer = "http://ah.189.cn/service/bill/fee.action?type=ticket";
            String templateUrl = "http://ah.189.cn/service/bill/sendValidReq.action?_v="+data;
            response = TaskHttpClient.create(param, RequestType.POST, "an_hui_10000_web_006").setFullUrl(templateUrl).setReferer(referer)
                    .invoke();
            String pageContent = response.getPageContent();
            if(StringUtils.contains(pageContent,"发送成功")){
                logger.info("详单-->短信验证码-->刷新成功,param={}", param);
                return result.success();
            }else {
                logger.error("详单-->短信验证码-->刷新失败,param={},pateContent={}", param, response.getPageContent());
                return result.failure(ErrorCode.REFESH_SMS_UNEXPECTED_RESULT);
            }
        }catch (Exception e){
            logger.error("详单-->短信验证码-->刷新失败,param={},response={}", param, response, e);
            return result.failure(ErrorCode.REFESH_SMS_ERROR);
        }
    }

    private HttpResult<Map<String,Object>> submitForBillDetail(OperatorParam param) {
        HttpResult<Map<String, Object>> result = new HttpResult<>();
        Response response = null;
        try{
            String templateUrl = "http://ah.189.cn/service/bill/phoneAndInternetDetail.action?rnd=" + Math.random();
            response = TaskHttpClient.create(param, RequestType.GET, "an_hui_10000_web_007").setFullUrl(templateUrl)
                    .invoke();
            String pageContent = response.getPageContent();
            String macCode = PatternUtils.group(pageContent, "id=\"macCode\"\\s*value=\"([^ ]+)\"", 1);
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            String data = "currentPage=&pageSize=10&effDate=" + format.format(new Date()) + "&expDate="
                    + format.format(new Date()) + "&serviceNbr=" + param.getMobile() + "&operListID=2&isPrepay=0&pOffrType=481&random="
                    + param.getSmsCode() + "&macCode=" + macCode;
            Invocable invocable = ScriptEngineUtil.createInvocableFromBase64(javaScript);
            templateUrl = "http://ah.189.cn/service/bill/feeDetailrecordList.action?_v="
                    +invocable.invokeFunction("encryptedString", data).toString();
            String referer = "http://ah.189.cn/service/bill/fee.action?type=phoneAndInternetDetail";
            response = TaskHttpClient.create(param, RequestType.POST, "an_hui_10000_web_008").setFullUrl(templateUrl).setReferer(referer)
                    .invoke();
            pageContent = response.getPageContent();
            if(StringUtils.contains(pageContent,"没有符合条件的记录") || StringUtils.contains(pageContent,"导出查询结果")) {
                logger.info("详单-->校验成功,param={}", param);
                return result.success();
            }else{
                logger.error("详单-->校验失败,param={},pageContent={}", param, response.getPageContent());
                return result.failure(ErrorCode.VALIDATE_UNEXPECTED_RESULT);
            }

        }catch (Exception e){
            logger.error("详单-->校验失败,param={},response={}", param, response, e);
            return result.failure(ErrorCode.VALIDATE_ERROR);
        }
    }

    private HttpResult<Object> processForPdf(OperatorParam param) {
        if (logger.isDebugEnabled()){
            logger.debug("start run exportPdf plugin!");
        }
        HttpResult<Object> result = new HttpResult<>();
        Map<String, String> resultMap = new LinkedHashMap<String, String>();
        Map<String, String> paramMap = (LinkedHashMap<String, String>) GsonUtils
                .fromJson(param.getArgs()[0], new TypeToken<LinkedHashMap<String, String>>() {}.getType());
        String templateUrl = paramMap.get("page_content");
        Response response = null;
        try{
            response = TaskHttpClient.create(param, RequestType.GET, "an_hui_10000_web_009").setFullUrl(templateUrl)
                    .invoke();
            byte[] bytes = response.getResponse();
            String htmlContent = org.apache.commons.lang.StringUtils.EMPTY;
            if (org.apache.commons.lang.StringUtils.isNotBlank(new String(bytes))) {
                htmlContent = PdfUtils.pdfToHtml(new ByteArrayInputStream(bytes));
            } else {
                htmlContent = "no data";
            }
            resultMap.put(PluginConstants.FIELD, htmlContent);
            if (logger.isDebugEnabled()){
                logger.debug("exportPdf plugin completed! resultMap:" + resultMap);
                return result.success(GsonUtils.toJson(resultMap));
            }else{
                logger.error("详单打印失败,param={},response={}", param, htmlContent);
                return result.failure(ErrorCode.UNKNOWN_REASON);
            }

        }catch (Exception e){
            logger.error("详单打印失败,param={},response={}", param, response, e);
            return result.failure(ErrorCode.UNKNOWN_REASON);
        }

    }

}
